### ISSUE TITLE
Occasional Failure Accrual issues during deployments

### ISSUE THREAD

**Issue by dpetersen** [linkerd/linkerd#1114]
I'm running linkerd 0.8.6 in Kubernetes with namerd. We've been running for months with some simple services, and for 3 weeks with a higher traffic service. I've had two deployments (of many dozens) now where my service has effectively been down when the deployment finished and required a linkerd restart to fix.

The first event was in production a couple of weeks ago. I haven't saved logs or metrics from that period. We have 2 linkerds behind a Kubernetes service for redundancy. We have prometheus scraping everything. One of the two linkerds decided that the Kubernetes service it was proxying to was unhealthy and took it out of the load balancer, while the other linkerd was happy with the service and continued working. Kubernetes still considered both linkerds healthy, and so half our requests were timing out.

The second event was in staging, where we have 1 linkerd. This time I have logs and metrics for it, so I'll go into more detail. The router is named `in-g5devops-public`, the Kubernetes namespace is `core-staging`, and the Kubernetes service is `core-client-center`. I did a deployment at ~11:10am PST. Our Docker images are somewhat enormous and it can take a minute or two for Kubernetes to actually start containers running the new code. We are using the `RollingUpdate` strategy for deploys, so new pods should be up and responding to web requests before the old pods are torn down.

Here's a graph from the event, and an hour leading up.

<img width="788" alt="screenshot" src="https://cloud.githubusercontent.com/assets/408/23480756/ec73dda8-fe7d-11e6-9405-da79e1d7bc2f.png">

We had a `failures:com_twitter_finagle_CancelledRequestException`, but that was almost 30 minutes before the load balancer `failure_accrual:removals` got bumped (which is when the downtime started). There aren't any other failures, according to the metrics.

Meanwhile, in the logs for linkerd, here's what I saw shortly after the deployment:
```
I 0301 19:14:10.514 THREAD26 TraceId:41d1489281960db3: FailureAccrualFactory marking connection to "#/io.l5d.k8s/core-staging/http/core-client-center" as dead. Remote Address: Inet(/100.96.14.55:80,Map(nodeName -> ip-172-20-32-180.us-west-2.compute.internal))
I 0301 19:14:15.549 THREAD26 TraceId:41d1489281960db3: FailureAccrualFactory marking connection to "#/io.l5d.k8s/core-staging/http/core-client-center" as dead. Remote Address: Inet(/100.96.14.55:80,Map(nodeName -> ip-172-20-32-180.us-west-2.compute.internal))
I 0301 19:14:21.329 THREAD26 TraceId:b6c72045b01065ce: FailureAccrualFactory marking connection to "#/io.l5d.k8s/core-staging/http/core-client-center" as dead. Remote Address: Inet(/100.96.14.55:80,Map(nodeName -> ip-172-20-32-180.us-west-2.compute.internal))
I 0301 19:14:36.759 THREAD26 TraceId:41d1489281960db3: FailureAccrualFactory marking connection to "#/io.l5d.k8s/core-staging/http/core-client-center" as dead. Remote Address: Inet(/100.96.14.55:80,Map(nodeName -> ip-172-20-32-180.us-west-2.compute.internal))
E 0301 19:15:05.032 THREAD19 TraceId:41d1489281960db3: service failure
```

That happened once, and then after that we saw this repeated over and over a couple of times per minute:
```
I 0301 19:15:12.769 THREAD26 TraceId:b41c73255d54babd: FailureAccrualFactory marking connection to "#/io.l5d.k8s/core-staging/http/core-client-center" as dead. Remote Address: Inet(/100.96.14.55:80,Map(nodeName -> ip-172-20-32-180.us-west-2.compute.internal))
E 0301 19:15:13.980 THREAD20 TraceId:b6c72045b01065ce: service failure
Failure(request cancelled. Remote Info: Upstream Address: /127.0.0.1:44352, Upstream Client Id: Not Available, Downstream Address: /100.96.14.55:80, Downstream Client Id: #/io.l5d.k8s/core-staging/http/core-client-center, Trace Id: e5baff41f8f96281.f48cd0717d0de7c4<:e5baff41f8f96281, flags=0x03) with RemoteInfo -> Upstream Address: /127.0.0.1:53622, Upstream Client Id: Not Available, Downstream Address: /100.96.14.55:80, Downstream Client Id: #/io.l5d.k8s/core-staging/http/core-client-center, Trace Id: b6c72045b01065ce.b6c72045b01065ce<:b6c72045b01065ce
Caused by: com.twitter.finagle.CancelledRequestException: request cancelled. Remote Info: Upstream Address: /127.0.0.1:44352, Upstream Client Id: Not Available, Downstream Address: /100.96.14.55:80, Downstream Client Id: #/io.l5d.k8s/core-staging/http/core-client-center, Trace Id: e5baff41f8f96281.f48cd0717d0de7c4<:e5baff41f8f96281
```

I wanted to try and troubleshoot the error, and so linkerd stayed in this condition for quite a while, like 20 minutes, as I poked around logs and metrics. There weren't any issues with our `core-client-center` containers, but linkerd never recovered and never put the service back in the load balancer. I eventually scaled linkerd down and back up, and everything started working again.

Here is my entire linkerd config. We're not modifying anything about how failure accrual should work:
```
  config.yaml: |-
    admin:
      port: 9990
    namers:
      - kind: io.l5d.k8s
        host: 127.0.0.1
        port: 8001
    telemetry:
      - kind: io.l5d.commonMetrics
      - kind: io.l5d.recentRequests
        sampleRate: 0.01
    routers:
      - protocol: http
        label: in-g5devops-public
        # undocumented, but got this from the linkerd slack to fix calls being
        # stripped of their usual headers and streamed, which breaks the call
        # player. There is an issue open about this behavior you might check up
        # on: https://github.com/linkerd/linkerd/issues/1071
        streamingEnabled: false
        # some core responses are insanely huge, like some client edit forms
        maxResponseKB: 10240
        servers:
          - port: 8080
            ip: 0.0.0.0
        interpreter:
          kind: io.l5d.namerd
          namespace: g5devops-public
          dst: /$/inet/namerd-sync/4100
```
