### ISSUE TITLE
Optional path consuming for the ingress identifier

### ISSUE THREAD

**Issue by esbie** [linkerd/linkerd#1144]
Similar to the path identifier, I suspect most folks will want the l5d ingress controller consume the beginning of the path used for routing.

One way to do this would be with ingress resource annotations, something like
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: "linkerd"
    linkerd/consume.segments: 2
```

Another would be in the linkerd config:
```
routers:
- protocol: http
  identifier:
    kind: io.l5d.http.ingress
    segments: 2
```

Or we could support both? I'm leaning towards ingress resource annotations since it would be the most flexible for users.

**Comment by 21stio** [comment]
Isn't the path identifier intended to be used for routing? At least that's how the mainstream implementations are behaving.
 
E.g. given the configuration below, `/foo/yo` would be routed to service listed in `-path: /foo`. 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: s1
          servicePort: 80
```

I actually don't see any need for providing additional vendor specific configuration. Please correct me if I'm wrong.. :)
