### ISSUE TITLE
TLS for ingress identifier

### ISSUE THREAD

**Issue by esbie** [linkerd/linkerd#1145]
As an ingress-controller, we ought to support tls as defined here: https://kubernetes.io/docs/user-guide/ingress/#tls

**Comment by esbie** [comment]
This issue is blocking potential features like https://github.com/jetstack/kube-lego integration for LetsEncrypt

**Comment by esbie** [comment]
Also, Istio support should include [tls via ingress resources](https://istio.io/docs/tasks/ingress.html#configuring-secure-ingress-https) (not necessarily SNI, but at least dynamic cert reloading)

**Comment by valdemon** [comment]
As this has been closed - does it mean the feature is perceived as unimportant and disappears from the Linkerd roadmap?

**Comment by wmorgan** [comment]
@klingerf and I chatted--closing was an oversight. Sorry. We still want to this. @valdemon do you have a use case for this feature?

**Comment by valdemon** [comment]
@klingerf Our use case leverages the automatic TLS certificate lifecycle management for services exposed via *k8s Ingress* using [LetsEncrypt](https://letsencrypt.org/) and the [kube-lego](https://github.com/jetstack/kube-lego) mentioned before by @esbie.

Currently I'm using [NGINX Ingress Controller](https://github.com/kubernetes/ingress-nginx) and it works for me well enough. We might be interested in switching to [Linkerd Ingress Controller](https://buoyant.io/2017/04/06/a-service-mesh-for-kubernetes-part-viii-linkerd-as-an-ingress-controller/) though, as soon as it provides this feature.

Except of having a single Ingress class (less of artifacts to deploy) I guess this would likely also give us better traceability (metrics) of network communication flow (provided by Linkerd-viz, Zipkin etc), starting already from the Ingress controller associated k8s service.

Below is our current Ingress example:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/secure-backends: "true"
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/hostname: "my-service.example.org."
    external-dns.alpha.kubernetes.io/ttl: 60
spec:
  tls:
    - hosts:
      - my-service.example.org
      secretName: my-service-ingress-tls
  rules:
  - host: my-service.example.org
    http:
      paths:
      - backend:
          serviceName: my-service
          servicePort: 4140
```
