### ISSUE TITLE
Timeouts from linkerd to namerd using mesh

### ISSUE THREAD

**Issue by DukeyToo** [linkerd/linkerd#1197]
Using linkerd 0.9.1 with config below, we get this error `com.twitter.finagle.RequestTimeoutException: exceeded 10.seconds to unspecified while dyn binding /http/x/y/z/1234. Remote Info: Not Available` during a small load test.  Before the load test, some manual requests work fine.

There are no network issues, and all nodes can easily talk to each other.  Running 3 namerd instances and about 20 linkerd instances.

linkerd (relevant parts only):
```
interpreter:
  kind: io.l5d.mesh
    dst: /$/inet/namerd.service.consul/4182
    experimental: true
    root: /default
  identifier:
    - kind: io.l5d.path
      segments: 5
    - kind: io.l5d.path
      segments: 4
    - kind: io.l5d.path
      segments: 3
    - kind: io.l5d.path
      segments: 2
    - kind: io.l5d.path
      segments: 1
```
namerd (complete):
```
admin:
  port: 9991
storage:
  kind: io.l5d.zk
  experimental: true
  zkAddrs:
  - host: 127.0.0.1
    port: 2181
  pathPrefix: /dtabs
  sessionTimeoutMs: 10000
namers:
- kind:      io.l5d.marathon
  experimental: true
  prefix:    /io.l5d.marathon
  host:      127.0.0.1
  port:      8080
  useHealthCheck: true
interfaces:
- kind: io.l5d.thriftNameInterpreter
  ip: 0.0.0.0
  port: 4100
- kind: io.l5d.httpController
  ip: 0.0.0.0
  port: 4181
- kind: io.l5d.mesh
  port: 4182
```

Any pointers on what could be causing this?

**Comment by klingerf** [comment]
@DukeyToo For your namerd `interfaces`, I see:

```
interfaces:
- kind: io.l5d.thriftNameInterpreter
  ip: 0.0.0.0
  port: 4100
- kind: io.l5d.httpController
  ip: 0.0.0.0
  port: 4181
- kind: io.l5d.mesh
  port: 4182
```

It looks like the `io.l5d.mesh` interface doesn't specify `port: 0.0.0.0`. Without that, I think namerd will only listen for connections to the mesh API from localhost. Can you try adding `port: 0.0.0.0` to see if that fixes it?

**Comment by olix0r** [comment]
i think the mesh api listens publicly by default.  @DukeyToo mentioned in slack that this behavior is seen with all interfaces.  my first guess is that it has something to do with storage:
```
  kind: io.l5d.zk
  experimental: true
  zkAddrs:
  - host: 127.0.0.1
    port: 2181
  pathPrefix: /dtabs
  sessionTimeoutMs: 10000
```

Is there a zookeeper on localhost with a directory /dtabs?

**Comment by DukeyToo** [comment]
Yes @olix0r  the zookeeper runs on same nodes as namerd.  

To be clear, this configuration works, until it doesn't.  At some point, linkerd => namerd communication breaks down and things break.

**Comment by olix0r** [comment]
can you grab a stats dump from both linkerd and namerd when it's in a bad state?  `linkerd:9990/admin/metrics.json?pretty=1` and `namerd:9991/admin/metrics.json?pretty=1`

**Comment by DukeyToo** [comment]
Thanks for the pointer @olix0r - I found what was causing this, and problem is no longer reproducible.   In my original report, I omitted the linkerd config that is to blame 👎 :
```
  identifier:
    - kind: io.l5d.path
      segments: 5
    - kind: io.l5d.path
      segments: 4
    - kind: io.l5d.path
      segments: 3
    - kind: io.l5d.path
      segments: 2
    - kind: io.l5d.path
      segments: 1
```

We did the above because we have varying lengths of paths that we need to support.  And it worked.  The 5 segment identifier would be presented with unique paths e.g. `/a/b/c/cust-123/things`, fail to match, and the next identifier would try to match, and eventually it would fall through to the 3 segment identifier and be matched successfully.

I think that the problem was that the 5 segment identifier still asked namerd to resolve the 5 segments, which caused a lot of load as each one was unique (because it contained a customer id).  Each unique 5 segment path was also being tracked individually in metrics and probably in in-memory cache.  Eventually, load got too much and things broke.
