### ISSUE TITLE
namerd rc4 docker images fails with missing openssl error

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd#1239]
I've been testing namerd rc4, and noticed that it's unable to serve the thriftNameInterpreter with tls configured. From the namerd logs, I see:

```
W 0424 23:05:55.377 UTC THREAD27 org.jboss.netty.channel.socket.nio.AbstractNioSelector: Failed to initialize an accepted socket.
java.io.IOException: Cannot run program "openssl": error=2, No such file or directory
```

Have verified that the same configuration works with namerd rc3. I think this issue stems from #1214.

**Comment by klingerf** [comment]
Here's the config file that I'm using that causes the failure in the description:

```
    admin:
      port: 9990

    namers:
    - kind: io.l5d.k8s
      host: localhost
      port: 8001

    storage:
      kind: io.l5d.k8s
      host: localhost
      port: 8001
      namespace: test

    interfaces:
    - kind: io.l5d.thriftNameInterpreter
      ip: 0.0.0.0
      port: 4100
    - kind: io.l5d.thriftNameInterpreter
      ip: 0.0.0.0
      port: 4101
      tls:
        certPath: /io.buoyant/namerd/certs/namerdcertificate.pem
        keyPath: /io.buoyant/namerd/certs/namerdkey.pem
    - kind: io.l5d.mesh
      ip: 0.0.0.0
      port: 4102
    - kind: io.l5d.httpController
      ip: 0.0.0.0
      port: 4180
```

The interface on 4101 is the one that's not serving traffic.
