### ISSUE TITLE
linkerd cannot communicate to namerd when using an AWS DNS name

### ISSUE THREAD

**Issue by rclayton-the-terrible** [linkerd/linkerd#1248]
We encountered a strange issue when launching linkerd and namerd on ECS.  We were trying to proxy namerd with an Application Load Balancer (using Target Group registration via ECS Service).  We can verify that the namerd instances are accessible through ALB, **even inside the linkerd container instance**:

```bash
docker exec -it 3026401c21d5 bash
curl http://namerd.example.com:4180/api/1/dtabs
# > ["ecs-production-entrypoint","ecs-production-microservices","ecs-qa-entrypoint","ecs-qa-microservices","entrypoint","microservices","resolve"]
```

However, when we start linkerd and attempt to communicate through one of the servers (or access the *dtab* page in the Admin portal, we get this error in the logs:

```
[rclayton@services-i-01ea82966325bf526 ~]$ docker logs -f 3026401c21d5
-XX:+AggressiveOpts -XX:+CMSClassUnloadingEnabled -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSParallelRemarkEnabled -XX:+CMSScavengeBeforeRemark -XX:InitialHeapSize=33554432 -XX:MaxHeapSize=1073741824 -XX:MaxNewSize=174485504 -XX:MaxTenuringThreshold=6 -XX:OldPLABSize=16 -XX:+PrintCommandLineFlags -XX:+ScavengeBeforeFullGC -XX:-TieredCompilation -XX:+UseCMSInitiatingOccupancyOnly -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseStringDeduplication
Apr 26, 2017 7:12:15 PM com.twitter.finagle.http.HttpMuxer$$anonfun$4 apply
INFO: HttpMuxer[/admin/metrics.json] = com.twitter.finagle.stats.MetricsExporter(<function1>)
Apr 26, 2017 7:12:15 PM com.twitter.finagle.http.HttpMuxer$$anonfun$4 apply
INFO: HttpMuxer[/admin/per_host_metrics.json] = com.twitter.finagle.stats.HostMetricsExporter(<function1>)
I 0426 19:12:15.780 UTC THREAD1: linkerd 1.0.0 (rev=72236b1f3e6feee77777321213b496ef7c3fed6a) built at 20170425-144355
I 0426 19:12:15.990 UTC THREAD1: Finagle version 6.41.0 (rev=95eedf5f41f78414fae25d93cc8fae02eeb5a75d) built at 20161220-164342
I 0426 19:12:17.087 UTC THREAD1: tracer: io.buoyant.telemetry.recentRequests.RecentRequetsTracer@7b733690
I 0426 19:12:17.269 UTC THREAD1: Tracer: com.twitter.finagle.zipkin.thrift.ScribeZipkinTracer
I 0426 19:12:17.351 UTC THREAD1: Resolver[inet] = com.twitter.finagle.InetResolver(com.twitter.finagle.InetResolver@3c69362a)
I 0426 19:12:17.352 UTC THREAD1: Resolver[neg] = com.twitter.finagle.NegResolver$(com.twitter.finagle.NegResolver$@29138d3a)
I 0426 19:12:17.351 UTC THREAD1: Resolver[fixedinet] = com.twitter.finagle.FixedInetResolver(com.twitter.finagle.FixedInetResolver@2412a42b)
I 0426 19:12:17.352 UTC THREAD1: Resolver[nil] = com.twitter.finagle.NilResolver$(com.twitter.finagle.NilResolver$@5cbe2654)
I 0426 19:12:17.353 UTC THREAD1: Resolver[fail] = com.twitter.finagle.FailResolver$(com.twitter.finagle.FailResolver$@496a31da)
I 0426 19:12:17.354 UTC THREAD1: Resolver[flag] = com.twitter.server.FlagResolver(com.twitter.server.FlagResolver@7c251f90)
I 0426 19:12:17.354 UTC THREAD1: Resolver[zk] = com.twitter.finagle.zookeeper.ZkResolver(com.twitter.finagle.zookeeper.ZkResolver@51841ac6)
I 0426 19:12:17.355 UTC THREAD1: Resolver[zk2] = com.twitter.finagle.serverset2.Zk2Resolver(com.twitter.finagle.serverset2.Zk2Resolver@5ba26eb0)
I 0426 19:12:17.642 UTC THREAD1: serving http admin on /0.0.0.0:9990
I 0426 19:12:17.656 UTC THREAD1: serving external-http on /0.0.0.0:4141
I 0426 19:12:17.980 UTC THREAD1: serving local-http on /0.0.0.0:4140
I 0426 19:12:17.990 UTC THREAD1: initialized
E 0426 19:13:10.193 UTC THREAD10 TraceId:ddfa8992f1692218: service failure
com.twitter.finagle.RequestTimeoutException: exceeded 10.seconds to unspecified while dyn binding /svc/campaign-service. Remote Info: Not Available
```

Our linkerd configuration (hostname redacted):

```yaml
admin:
  port: 9990
routers:
- label: external-http
  protocol: http
  servers:
  - port: 4141
    ip: 0.0.0.0
    engine:
      # Default is netty3, but will be replaced in future to netty4
      kind: netty4
  interpreter:
    kind: io.l5d.namerd.http
    experimental: true
    namespace: entrypoint
    dst: /$/inet/namerd.example.com/4180
- label: local-http
  protocol: http
  servers:
  - port: 4140
    ip: 0.0.0.0
    engine:
      # Default is netty3, but will be replaced in future to netty4
      kind: netty4
  interpreter:
    kind: io.l5d.namerd.http
    experimental: true
    namespace: microservices
    dst: /$/inet/namerd.example.com/4180
usage:
  enabled: false
telemetry:
- kind: io.l5d.recentRequests
  sampleRate: 1.0
  capacity: 100
```

And our namerd config:

```yaml
admin:
  ip: 0.0.0.0
  port: 9991
interfaces:
  - kind: io.l5d.thriftNameInterpreter
    ip: 0.0.0.0
    port: 4100
  - kind: io.l5d.httpController
    ip: 0.0.0.0
    port: 4180
namers:
  - kind: io.l5d.consul
    # Host IP acquired via AWS metadata endpoint
    host: 10.0.1.123
    prefix: /consul
storage:
  kind: io.l5d.consul
  experimental: true
  # Host IP acquired via AWS metadata endpoint
  host: 10.0.1.123
  # this is default path in Consul where
  # Dtab routing info will be looked up.
  pathPrefix: /namerd/dtabs
```

Our dtab was pretty basic:

```
/svc => /$/io.buoyant.http.domainToPathPfx/logical;
/logical/production/campaign-service => /actual/production/campaign-service.b1;
/actual => /#/consul/eu-central-1;
```

We've worked around the issue by launching namerd as sidecars on our ECS Hosts and dynamically writing the linkerd config to access the local instance.  However, it doesn't work trying various DNS names (EC2 Private DNS, Route 53, ALB DNS name).

This is our ECS Task Definition:

```
{
    "networkMode": "host",
    "taskRoleArn": null,
    "containerDefinitions": [
        {
            "volumesFrom": [],
            "memory": 512,
            "extraHosts": null,
            "dnsServers": null,
            "disableNetworking": null,
            "dnsSearchDomains": null,
            "portMappings": [
                {
                    "hostPort": 4141,
                    "containerPort": 4141,
                    "protocol": "tcp"
                },
                {
                    "hostPort": 4140,
                    "containerPort": 4140,
                    "protocol": "tcp"
                },
                {
                    "hostPort": 9990,
                    "containerPort": 9990,
                    "protocol": "tcp"
                }
            ],
            "hostname": null,
            "essential": true,
            "entryPoint": null,
            "mountPoints": [
                {
                    "containerPath": "/etc/linkerd/",
                    "sourceVolume": "config",
                    "readOnly": true
                }
            ],
            "name": "linkerd",
            "ulimits": null,
            "dockerSecurityOptions": null,
            "environment": [
                {
                    "name": "SERVICE_9990_CHECK_INTERVAL",
                    "value": "15s"
                },
                {
                    "name": "SERVICE_4141_NAME",
                    "value": "linkerd-external-http"
                },
                {
                    "name": "SERVICE_4141_CHECK_INTERVAL",
                    "value": "15s"
                },
                {
                    "name": "SERVICE_9990_CHECK_TCP",
                    "value": "true"
                },
                {
                    "name": "SERVICE_4141_CHECK_TCP",
                    "value": "true"
                },
                {
                    "name": "SERVICE_4140_CHECK_INTERVAL",
                    "value": "15s"
                },
                {
                    "name": "SERVICE_9990_NAME",
                    "value": "linkerd-admin"
                },
                {
                    "name": "SERVICE_4140_CHECK_TCP",
                    "value": "true"
                },
                {
                    "name": "SERVICE",
                    "value": "linkerd"
                },
                {
                    "name": "SERVICE_4140_CHECK_TIMEOUT",
                    "value": "1s"
                },
                {
                    "name": "SERVICE_9990_CHECK_TIMEOUT",
                    "value": "1s"
                },
                {
                    "name": "SERVICE_4140_NAME",
                    "value": "linkerd-local-http"
                },
                {
                    "name": "SERVICE_4141_CHECK_TIMEOUT",
                    "value": "1s"
                }
            ],
            "links": null,
            "workingDirectory": null,
            "readonlyRootFilesystem": null,
            "image": "buoyantio/linkerd:1.0.0",
            "command": [
                "/etc/linkerd/linkerd.yml"
            ],
            "user": null,
            "dockerLabels": null,
            "logConfiguration": {
                "logDriver": "json-file",
                "options": {
                    "max-size": "50m",
                    "max-file": "10"
                }
            },
            "cpu": 0,
            "privileged": null,
            "memoryReservation": 256
        }
    ],
    "placementConstraints": [],
    "volumes": [
        {
            "host": {
                "sourcePath": "/opt/services/linkerd/"
            },
            "name": "config"
        }
    ],
    "family": "linkerd"
}
```
