### ISSUE TITLE
Production readiness guidelines: Resource Requests and Limits in Kubernetes

### ISSUE THREAD

**Issue by robb-foster-ck** [linkerd/linkerd#1259]
It would be helpful if Linkerd and Namerd provided [liveliness and readiness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/), along with memory and CPU requests and limits recommendations for running in K8S.  Hopefully, there could also be provided an endpoint to administratively toggle the state of the readiness probe, so that a Linkerd instance could be taken out of service without needing to terminate it.

**Comment by adleong** [comment]
1. Liveness: linkerd has an /admin/ping endpoint
2. Readiness: in the finagle philosophy, the best way to test readiness is to simply send an end-to-end request and see if it can be served.  For example, sending a health check request to the destination service through linkerd.  The benefit of this is that readiness is checked all the way through the system instead of just at the first hop.
3. Resource requests/limits: we should add this to our production readiness guide https://github.com/linkerd/linkerd/wiki/Going-to-production

I'll rename this ticket and keep it open to track number 3.

**Comment by wmorgan** [comment]
What's the recommendation for how to use Kubernetes readiness probes with Linkerd? We may want to add that as well to the going-to-prod doc.

**Comment by aschepis** [comment]
when you get to surveying real world data, i can provide some.

**Comment by SamFleming** [comment]
Just wondering if there's been any more thoughts on this? 

For the time being I've set both my liveness and readiness checks to the same endpoint and am hoping that'll be okay.

```yaml
livenessProbe:
  httpGet:
    path: /admin/ping
    port: 9990
  initialDelaySeconds: 40
  periodSeconds: 3
readinessProbe:
  httpGet:
    path: /admin/ping
    port: 9990
  initialDelaySeconds: 40
  periodSeconds: 5
```

**Comment by wmorgan** [comment]
@SamFleming that doesn't sound unreasonable. how's it working out?

**Comment by SamFleming** [comment]
Seemingly okay, no problem so far. 👍

**Comment by wmorgan** [comment]
Great. I'm going to label this as a documentation issue, since it doesn't sound like we will be doing feature work to support this.

**Comment by betson-nuovo** [comment]
In our l5d configuration (k8s daemonset with configmap), we've found that the /admin/ping endpoint alone is not sufficient in checking the health of l5d pods and have encountered situations where that endpoint returns successfully, while the l5d pod fails to proxy requests.  Initially, we have attempted to route through the local proxy port to the /admin/ping endpoint and that did provide better stability, but have found that pods would fail for other types of requests. In these scenarios, a pod redeploy resolves the issue.

Over multiple iterations, we've found that a single endpoint is insufficient for testing the health of an l5d pod as we've discovered **different** l5d pods in the **same** k8s cluster failing in **different** ways. This was confirmed by executing a custom troubleshooting script, which ran a series of tests against every l5d pod in a cluster, modeling various requests that could potentially route through the pod in our environment and resulted in a different set of test failures for different pods ( sampling of tests executed: HTTP 1.1 GET/POST, one-way SSL GET/POST, two-way ssl GET/POST, including self-signed CA certs, to services within the cluster and third-party services outside the cluster, ie google).

The current iteration of our health check for l5d consists of using the k8s liveness/readiness [ExecAction](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes) command to run a shell script consisting of a similar series of tests against the l5d pod.

A reduced version of our current liveness check (similar for readiness):
```yaml
livenessProbe:
    exec:
    command:
    - bash
    - -c
    - export http_proxy=$POD_IP:4140; declare -a httpUrl; httpUrl[0]="curl -v -w '%{http_code}' -s  -o /dev/null --max-time 2 http://$POD_IP:9990/admin/ping"; httpUrl[1]="curl -v -w '%{http_code}' -s  -o /dev/null --max-time 2 http://redactedurl" for i in "${httpUrl[@]}"; do resp="$(eval $i)"; if [ "$resp" -eq 200 ]; then echo "success"; else  echo "failure"; export http_proxy=; exit 1; fi; done; export http_proxy=; exit 0;
    initialDelaySeconds: 90
    periodSeconds: 25
    timeoutSeconds: 25
```
Hope this helps
