### ISSUE TITLE
Identifier does not return on first successful match

### ISSUE THREAD

**Issue by smparekh** [linkerd/linkerd#1260]
According to linkerd docs: https://linkerd.io/config/1.0.0/linkerd/index.html#http-1-1-identifiers

> If a list of identifiers is provided, each identifier is tried in turn until one successfully assigns a logical name to the request.

If I have a list of identifier as:
```
routers:
- protocol: http
  identifier:
    kind: io.l5d.header.token
    header: Custom-Header
  identifier:
    kind: io.l5d.path
    segments: 1
    consume: true
```
I would expect linkerd to return if the Custom-Header is included in the request and a match is made (not try path identifier). Currently I am seeing linkerd still try to route the service to the constructed path when the header is included. 
```
$ http GET linkerd:4140/api/v1/hello Custom-Header:hello-world
HTTP/1.1 502 Bad Gateway
Content-Encoding: gzip
Content-Length: 106
Content-Type: text/plain
l5d-err: No+hosts+are+available+for+%2Fsvc%2Fapi%2C+Dtab.base%3D%5B%5D%2C+Dtab.local%3D%5B%5D.+Remote+Info%3A+Not+Available

No hosts are available for /svc/api, Dtab.base=[], Dtab.local=[]. Remote Info: Not Available
```

The service works correctly when I try to use the path identifier with and without the header.

If I reverse the order of the identifiers in the config I get a different error when using only path identifier with no Custom-Header:
```
Unknown Destination: Request("GET /hello-world/api/v1/hello", from /x.x.x.x:xxxx) / Custom-Header is absent.
```
Is this expected behavior?

**Comment by adleong** [comment]
You have the `identifier` property set twice in your linkerd config which will cause the first identifier to be overriden/replaced by the second one.  Instead, you should provide a list of identifiers:

```
routers:
- protocol: http
  identifier:
  - kind: io.l5d.header.token
    header: Custom-Header
  - kind: io.l5d.path
    segments: 1
    consume: true
```

The difference is pretty subtle.  I've filed https://github.com/linkerd/linkerd/issues/1262 to make it so that duplicate properties will raise an error.

**Comment by smparekh** [comment]
Not sure why this was closed, the documentation explicitly states you can have multiple identifiers and linkerd _should_ try each one in succession.

**Comment by adleong** [comment]
Hi @smparekh.  That's right, you can have multiple identifiers but they must be defined as a list like the example in my last comment.  I know the documentation of this isn't 100% clear and could use an example.  

These docs live [here](https://github.com/linkerd/linkerd/blob/master/linkerd/docs/protocol-http.md) in the linkerd repo and we gladly accept pull requests if you'd like to help us improve them.

**Comment by smparekh** [comment]
Ok, not sure if this is expected or not either:

If I include the path kind first the request fails but if I include the header.token first in the list the request works for both identifier techniques path and header.

Once we verify this is expected I can create a PR for the docs.

**Comment by adleong** [comment]
If I put the path identifier first it uses the path segment if it's present, otherwise falls back to the header:

```
$ curl localhost:4140/foo -H "Custom-Header: bar"
No hosts are available for /svc/foo, Dtab.base=[/svc=>/#/io.l5d.fs], Dtab.local=[]. Remote Info: Not Available
$ curl localhost:4140 -H "Custom-Header: bar"
No hosts are available for /svc/bar, Dtab.base=[/svc=>/#/io.l5d.fs], Dtab.local=[]. Remote Info: Not Available
```

Here's the config: 
```
namers:
- kind: io.l5d.fs
  rootDir: linkerd/examples/io.l5d.fs

routers:
- protocol: http
  dtab: /svc => /#/io.l5d.fs
  identifier:
  - kind: io.l5d.path
    segments: 1
    consume: true
  - kind: io.l5d.header.token
    header: Custom-Header
  servers:
  - port: 4140
```

This is in line with what I would expect.  Does that answer your question?

**Comment by smparekh** [comment]
If I have the path first, it definitely does not like routing it with the header included:
Including my tests and config:
```
sparekh@linux-sparekh:~$ http GET linkerd:4140/hello-world/api/v1/hello Custom-Header:hello-world
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Length: 106
Via: 1.1 linkerd
content-type: application/json

{
    "hello": "world"
}

sparekh@linux-sparekh:~$ http GET linkerd:4140/api/v1/hello Custom-Header:hello-world
HTTP/1.1 502 Bad Gateway
Content-Encoding: gzip
Content-Length: 106
Content-Type: text/plain
l5d-err: No+hosts+are+available+for+%2Fsvc%2Fapi%2C+Dtab.base%3D%5B%5D%2C+Dtab.local%3D%5B%5D.+Remote+Info%3A+Not+Available

No hosts are available for /svc/api, Dtab.base=[], Dtab.local=[]. Remote Info: Not Available
```
Linkerd config:
```
admin:
  port: 9990

telemetry:
- kind: io.l5d.prometheus

routers:
- protocol: http
  identifier:
#    - kind: io.l5d.header.token
#      header: OW-App-Id
    - kind: io.l5d.path
      segments: 1
      consume: true
    - kind: io.l5d.header.token
      header: Custom-Header
  client:
    loadBalancer:
      kind: ewma
      maxEffort: 10
      decayTimeMs: 15000
  servers:
  - port: 4140
    ip: 0.0.0.0
  label: linkerd_proxy
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/x.x.x.x/4100
```
