### ISSUE TITLE
gRPC/HTTP2 proxy issues (perhaps Go specific)

### ISSUE THREAD

**Issue by arbarlow** [linkerd/linkerd#1301]
**Desired behaviour:**
Using linkerd as a proxy with a gRPC client and gRPC server works transparently to the client and server.

**Actual behaviour:**
gRPC client attempts to do a http `CONNECT` which fails.

**Setup**
gRPC Go: 1.4.0
Using the gRPC go[ 'hello world' examples](https://github.com/grpc/grpc-go/tree/master/examples/helloworld) (modify the client to send requests to 'world' instead of 'localhost'), then running..

`http_proxy=localhost:4140 go run main.go`

This causes the client to hang, as it will issue a http `CONNECT` to connect to the proxy, but seems to get no reply.

Wireshark shows this like the following..

![screen shot 2017-05-12 at 15 28 48](https://cloud.githubusercontent.com/assets/106357/26002502/c1a296ea-3727-11e7-86bf-a327b9ff6448.png)

This is obviously a http/1.0 request so I wonder if linkerd's `h2` doesn't like that.

Commenting out this line in gRPC-Go works as it uses the proxy, but skips the `CONNECT`: https://github.com/grpc/grpc-go/blob/master/proxy.go#L141

My linkerd config is the following..

```yaml
admin:
  port: 9990

routers:
- protocol: h2
  label: proxy
  experimental: true
  identifier:
    kind: io.l5d.header.token
  dtab: /svc => /$/inet/192.168.0.10/50051
  servers:
  - ip: 0.0.0.0
    port: 4140
```

`192.168.0.10/50051` being where my Go server is located

I'm not sure which party is exactly the failing party here, but it does seem that linkerd doesn't even send a response of any kind? I'm happy to help debug/fix and if need contribute back to gRPC go to fix any issues on the Go side. But I'm probably not much help on the linkerd side!
