### ISSUE TITLE
Need a deployment config for kubernetes with RBAC

### ISSUE THREAD

**Issue by turchanov** [linkerd/linkerd#1347]
Linkerd cannot retrieve endpoint list when deployed on kubernetes 1.6 using deployment configs as instructed https://linkerd.io/getting-started/k8s/ or https://linkerd.io/getting-started/k8s-daemonset/. This happends due to RBAC being turned on by default for kubernetes 1.6.

I circuvmented RBAC by permitting everything to `default` ServiceAccount used to run linkerd pod (see below).

We need a deployment config for kubernetes with RBAC with fine-grained `Role` (or `ClusterRole`? I am not an expert on Kubernetes).

If anyone needs the stack trace thown by linkerd, it is here #1344.

```
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: linkerd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: linkerd-allow-all
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: linkerd-allow-all
rules:
  - apiGroups: [""]
    resources:
      - '*'
    verbs:
      - '*'
```

**Comment by adleong** [comment]
I believe linkerd can get away with much more restrictive permissions than the ones granted above.  It should only need read and watch permissions on the endpoints, namespaces, and services APIs. 

Thanks for the issue, we'll definitely put something together.

**Comment by ethanrubio** [comment]
I'm also running into issues with namerd trying to get the dtabs.l5d.io from the thirdpartyresource found [here](https://github.com/linkerd/linkerd-examples/blob/master/k8s-daemonset/k8s/namerd.yml). 

```
io.buoyant.k8s.Api$UnexpectedResponse: Response("HTTP/1.1 Status(403)"): User "system:serviceaccount:default:default" cannot list dtabs.l5d.io in the namespace "default".
	at io.buoyant.k8s.Api$.parse(Api.scala:72)
	at io.buoyant.k8s.ListResource.$anonfun$get$2(resources.scala:136)
	at com.twitter.util.Future.$anonfun$flatMap$1(Future.scala:1089)
	at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:107)
	at com.twitter.util.Promise$Transformer.k(Promise.scala:107)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:117)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:98)
```

I've allowed linkerd and namerd to have all permissions as mentioned above:
```
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: linkerd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: linkerd-allow-all
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: linkerd-allow-all
rules:
  - apiGroups: [""]
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: namerd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namerd-allow-all
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: namerd-allow-all
rules:
  - apiGroups: [""]
    resources:
      - '*'
    verbs:
      - '*'
```

How can I let namerd have permissions to get the dtabs from the third party resource?

**Comment by ethanrubio** [comment]
A quick update I solved it by doing the following:

```
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  name: namerd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  name: namerctl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  name: namerctl-script
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
```
Is there a better way to do this than granting cluster-admin access?
