### ISSUE TITLE
Automatic env var substitution in linkerd config files

### ISSUE THREAD

**Issue by kevholditch** [linkerd/linkerd#1450]
Support automatic replacement of environment variables in the linkerd.conf file when linkerd starts up.

This is useful in a number of scenarios when parts of the config are not known until runtime especially when running in a docker container ([see my blog post for a real world scenario](https://kevinholditch.co.uk/2017/06/28/running-linkerd-in-a-docker-container-on-aws-ecs/)).

The format of the variable in the config file could be prefixed with a '$' for example:

```
interpreter:
kind: default
    transformers:
    – kind: io.l5d.specificHost
    host: $LOCAL_IP
```

Here $LOCAL_IP would be replaced with the value found at runtime in the environment variable LOCAL_IP.
