### ISSUE TITLE
Linkerd file base service recovery is not working

### ISSUE THREAD

**Issue by mnnit-geek** [linkerd/linkerd#1462]
Hi,
I'm not able to use file based service discovery. 
Here is my directory structure:
[root@ip-172-23-1-207 aman]# ls
config  disco  index.html  linkerd-1.0.2-exec  upload

LinkerD config file looks like this:
```
[root@ip-172-23-1-207 aman]# cat config/linkerd-fs.yml
namers:
- kind: io.l5d.fs
  rootDir: disco

admin:
  ip: 172.23.1.207
  port: 8888

routers:
- protocol: http
  dtab:
        /svc => /#/io.l5d.fs ;
  servers:
  - port: 7777

telemetry:
- kind: io.l5d.recentRequests
  sampleRate: 1.0
```

[root@ip-172-23-1-207 aman]# cat disco/dcs
172.23.1.211 1212
172.23.1.133 1212
172.23.1.207 1212

Now, if I add any new server under dcs for example:
[root@ip-172-23-1-207 aman]# cat disco/dcs
172.23.1.211 1212
172.23.1.133 1212
172.23.1.207 1212
172.23.1.130 1212

The requests are not getting routed to the new VM unless I restart the LinkerD. Please suggest what could be wrong here?
