### ISSUE TITLE
[1.1.0] Linkerd OOMs on too many distinct names

### ISSUE THREAD

**Issue by Ashald** [linkerd/linkerd#1486]
Was chasing another issue in v1.1.0 but hit this with a next test-case:

```yaml
admin:
  port: ${PORT_ADMIN}

namers:
- kind: io.l5d.consul
  useHealthCheck: true
  consistencyMode: stale
  prefix: /consul

routers:
- protocol: http
  label: egress
  maxRequestKB: 51200
  maxResponseKB: 51200
  maxInitialLineKB: 10
  maxHeadersKB: 65
  dstPrefix: /http
  identifier:
    - kind: io.l5d.header.token
      header: Host
  interpreter:
    kind: io.l5d.mesh
    dst: /#/consul/.local/namerd-grpc
    root: /default
    experimental: true
  servers:
    - port: ${PORT_HTTP}
      ip: 0.0.0.0
```
Then just send requests with increasing length of the URI:
```bash
$ for n in {1..65000}; do; echo $n; curl -x localhost:${PORT_HTTP} -m1 "http://$(printf 'x%.0s' {1..$n}).com" &>/dev/null; done
```

Eventually linkerd crashes with messages like this one:
```
Exception in thread "finagle/netty3-9" java.lang.OutOfMemoryError: Java heap space
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "finagle/netty3-9"

VM error: Java heap space
java.lang.OutOfMemoryError: Java heap space
VM error: Java heap space
java.lang.OutOfMemoryError: Java heap space
VM error: Java heap space
java.lang.OutOfMemoryError: Java heap space
VM error: Java heap space
java.lang.OutOfMemoryError: Java heap space
VM error: Java heap space
java.lang.OutOfMemoryError: Java heap space
VM error: Java heap space
java.lang.OutOfMemoryError: Java heap space
VM error: Java heap space
java.lang.OutOfMemoryError: Java heap space
VM error: Java heap space
java.lang.OutOfMemoryError: Java heap space
VM error: Java heap space
Exception in thread "RawZipkinTracer-ShutdownHook" java.lang.InternalError: BMH.reinvoke=Lambda(a0:L/SpeciesData<L>,a1:L,a2:L,a3:L)=>{
    t4:L=MethodHandleImpl.array();
    t5:L=Species_L.argL0(a0:L);
    t6:L=MethodHandle.invokeBasic(t5:L,a1:L,a2:L,a3:L,t4:L);t6:L}
	at java.lang.invoke.MethodHandleStatics.newInternalError(MethodHandleStatics.java:127)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "RawZipkinTracer-ShutdownHook"
java.lang.OutOfMemoryError: Java heap space
```
