### ISSUE TITLE
OutOfMemory Errors with namerd and Consul

### ISSUE THREAD

**Issue by eduponte** [linkerd/linkerd#1487]
Moving away from https://github.com/linkerd/linkerd/issues/1361 since it describes a different scenario.

We are seeing a issue similar to the above mentioned with Namerd (v1.1.0) using the Consul Namer and the Consul Storage Backend. We run three Namerd instances behind a load balancer and we are consistently getting out-of-memory errors even after increasing the hard and soft limit in Docker and the heap size in the JVM. We're now at 1024m of memory and nodes fail approximately every 8 hours.

![screen shot 2017-07-11 at 14 50 41](https://user-images.githubusercontent.com/2582479/28069081-69a4c5ee-6648-11e7-9717-80b5a80a867e.png)

We activated the admin route and were able to capture the situation in a near-to-crash slot:

- [On 83% memory usage](https://github.com/linkerd/linkerd/issues/1361#issuecomment-313363444)
- [On 95% memory usage](https://github.com/linkerd/linkerd/issues/1361#issuecomment-313392973)
- [About to crash](https://github.com/linkerd/linkerd/issues/1361#issuecomment-313428520)

@olix0r mentioned [something was probably going wrong with the consul client](https://github.com/linkerd/linkerd/issues/1361#issuecomment-313479743).

Here's a `namerd.yml` configuration that could help to reproduce the issue:

```
admin:
  ip: 0.0.0.0
  port: 9991
interfaces:
  - kind: io.l5d.thriftNameInterpreter
    ip: 0.0.0.0
    port: 4100
  - kind: io.l5d.httpController
    ip: 0.0.0.0
    port: 4180
namers:
  - kind: io.l5d.consul
    host: X.X.X.X
    prefix: /consul
    includeTag: true
storage:
  kind: io.l5d.consul
  experimental: true
  host: X.X.X.X
  pathPrefix: /namerd/dtabs
```
