### ISSUE TITLE
io.l5d.specificHost does not render host param in config.json admin endpoint

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd#1515]
given the following config block:

```yaml
routers:
- protocol: http
  interpreter:
    kind: default
    transformers:
    - kind: io.l5d.specificHost
      host: 192.168.99.100
```

the `/config.json` endpoint does not render the value of `host`:

```bash
curl -s 192.168.99.100:9990/config.json|jq .routers[1].interpreter.transformers
[
  {
    "kind": "io.l5d.specificHost"
  }
]
```
