### ISSUE TITLE
Marathon group names resolve issue

### ISSUE THREAD

**Issue by vadimi** [linkerd/linkerd#1531]
Hello,

I use marathon namer with `h2` router and trying to resolve names that include groups: `mygroup/my-service`. Everything works fine when I do it from linkerd dtab page, but when I connect from `gRPC` client I get the following error in the log:

`com.twitter.finagle.NoBrokersAvailableException: No hosts are available for /svc/\6d\x79\x67\x72\x6f\x75\x70\x2f\x6d\x79\x2d\x73\x65\x72\x76\x69\x63\x65, Dtab.base=[/ph=>/$/io.buoyant.rinet;/srv=>/$/io.buoyant.porthostPfx/ph;/svc=>/srv;/marathonId=>/#/io.l5d.marathon;/svc=>/$/io.buoyant.http.domainToPathPfx/marathonId], Dtab.local=[]. Remote Info: Not Available
`

I can successfully resolve names when I use the following format: `my-service.mygroup`

**Comment by olix0r** [comment]
Hey @vadimi.  This looks to me like you're using _token_ identifier instead of a _path_ identifier?  Can you share your linkerd config?

**Comment by vadimi** [comment]
Yes, I use token identifier. Should I use path instead?

Here is my config:

```
admin:
  port: 9990
namers:
- kind: io.l5d.marathon
  host: leader.mesos
  port: 443
  uriPrefix: "/marathon"
  prefix: "/io.l5d.marathon"
  tls:
    commonName: master.mesos
    trustCerts:
    - "/mnt/mesos/sandbox/.ssl/ca.crt"
routers:
- protocol: h2
  experimental: true
  identifier:
    kind: io.l5d.header.token
  dtab: >-
  	/ph=>/$/io.buoyant.rinet;
  	/srv=>/$/io.buoyant.porthostPfx/ph;
  	/svc=>/srv;/marathonId=>/#/io.l5d.marathon
        /svc=>/$/io.buoyant.http.domainToPathPfx/marathonId
  servers:
  - port: 4140
    ip: 0.0.0.0
```
