### ISSUE TITLE
io.l5d.ingress matches to default backends too eagerly

### ISSUE THREAD

**Issue by mejran** [linkerd/linkerd#1566]
I have an ingress rule in the namespace logging. When I use this configuration it doesn't trigger however all default ingress rules do trigger:
```
    namers:
    - kind: io.l5d.k8s
    routers:
    - protocol: http
      identifier:
        - kind: io.l5d.ingress
      servers:
        - port: 80
          ip: 0.0.0.0
      dtab: >-
        /svc => /#/io.l5d.k8s;
```

If I user this configuration it does trigger:
```
    namers:
    - kind: io.l5d.k8s
    routers:
    - protocol: http
      identifier:
        - kind: io.l5d.ingress
          namespace: logging
      servers:
        - port: 80
          ip: 0.0.0.0
      dtab: >-
        /svc => /#/io.l5d.k8s;
```

According to the documentation the second configuration should load ingress from all namespaces (logging and default) however it appears to only load them from default.
