### ISSUE TITLE
Support TLS-encrypted communication with Consul

### ISSUE THREAD

**Issue by d10i** [linkerd/linkerd#1577]
Consul supports TLS-encrypted communication using HTTPS (see https://www.consul.io/docs/agent/options.html#example-configuration-file-with-tls). When using the `io.l5d.consul` namer there is no way to specify what  CA certificate to use (and client certificate+key path in case of client authentication). Requests are always sent via HTTP, not matter what port is specified.

It would be great if it was possible to specify the TLS params, similarly to the way clients are configured. Example:
```
namers:
- kind: io.l5d.consul
  host: ...
  port: ...
  tls:
    commonName: linkerd.io
    trustCerts:
    - /certificates/cacert.pem
    clientAuth:
      certPath: /certificates/cert.pem
      keyPath: /certificates/key.pem
```
