### ISSUE TITLE
High CPU and memory usage with frequent k8s state changes

### ISSUE THREAD

**Issue by aaronyoungkash** [linkerd/linkerd#1585]
Testing linkerd in my perf environment I noticed that namerd cpu and memory spike when my pods frequently cycle their readiness state. When I moved my dtabs into linkerd I got the same result there. This being a perf setup the pods report that they're not ready when they're at maximum capacity, so they flip back and forth unusually quickly. Note that in this case I'm not even using linkerd/namerd for anything: they're freshly installed and nothing has it set as it's proxy.

I was able to reproduce this issue with a minimal install which I will attach. In what I've found is it will behave for a few minutes until eventually spiking cpu to 100%, and memory climbing until the pod runs out of memory and restarts.

l5d.yaml:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: l5d-config
data:
  config.yaml: |-
    admin:
      port: 9990

    namers:
    - kind: io.l5d.k8s
      experimental: true
      host: localhost
      port: 8001

    telemetry:
    - kind: io.l5d.prometheus
    - kind: io.l5d.recentRequests
      sampleRate: 0.25

    usage:
      orgId: linkerd-examples-daemonset

    routers:
    - protocol: http
      label: outgoing
      dtab: |
        /srv        => /#/io.l5d.k8s/default/http;
        /svc        => /srv;
      interpreter:
        kind: default
        transformers:
        - kind: io.l5d.k8s.daemonset
          namespace: default
          port: incoming
          service: l5d
      servers:
      - port: 4140
        ip: 0.0.0.0
      service:
        responseClassifier:
          kind: io.l5d.http.retryableRead5XX

    - protocol: http
      label: incoming
      dtab: |
        /srv        => /#/io.l5d.k8s/default/http;
        /host       => /srv;
        /svc        => /host;
      interpreter:
        kind: default
        transformers:
        - kind: io.l5d.k8s.localnode
      servers:
      - port: 4141
        ip: 0.0.0.0
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: l5d
  name: l5d
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        app: l5d
    spec:
      volumes:
      - name: l5d-config
        configMap:
          name: "l5d-config"
      containers:
      - name: l5d
        image: buoyantio/linkerd:1.1.3
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - -log.level=DEBUG
        - -com.twitter.finagle.tracing.debugTrace=true
        - /io.buoyant/linkerd/config/config.yaml
        ports:
        - name: outgoing
          containerPort: 4140
          hostPort: 4140
        - name: incoming
          containerPort: 4141
        - name: admin
          containerPort: 9990
        volumeMounts:
        - name: "l5d-config"
          mountPath: "/io.buoyant/linkerd/config"
          readOnly: true

      - name: kubectl
        image: buoyantio/kubectl:v1.6.2
        args: ["proxy", "-p", "8001"]
---
apiVersion: v1
kind: Service
metadata:
  name: l5d
spec:
  selector:
    app: l5d
  type: LoadBalancer
  ports:
  - name: outgoing
    port: 4140
  - name: incoming
    port: 4141
  - name: admin
    port: 9990
```

ready.yaml:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ready-config
data:
  server.js: |-
    const http = require('http');
    const port = 8080;

    let flipper = Math.floor(Math.random() * 1000);

    const requestHandler = (request, response) => {
      console.log(request.url, ++flipper);
      if (Math.floor(flipper / 3) % 2 === 0) {
        response.statusCode = 500;
        response.end('Nope!');
      }
      else {
        response.end('Hello Node.js Server!');
      }
    }

    const server = http.createServer(requestHandler);

    server.listen(port, (err) => {
      if (err) {
        return console.log('something bad happened', err);
      }

      console.log(`server is listening on ${port}`);
    });
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ready-deployment
spec:
  replicas: 50
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: ready
    spec:
      volumes:
      - name: ready-config
        configMap:
          name: "ready-config"
      containers:
      - name: ready
        image: node
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 6
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: "ready-config"
          mountPath: "/ready"
          readOnly: true
        args: ["node", "/ready/server.js"]
---
apiVersion: v1
kind: Service
metadata:
  name: ready
spec:
  selector:
    app: ready
  clusterIP: None
  ports:
  - name: http
    port: 8080
```
