### ISSUE TITLE
HTTP 504 Gateway timeouts after upgrading to linkerd 1.2.0

### ISSUE THREAD

**Issue by kumudt** [linkerd/linkerd#1636]
## Filing a linkerd issue ##

Issue Type: Bug Report

**What happened**:
We have a rails application which serves web pages and it was running as a Kubernetes deployment. Every time a deployment is made and new pods come up, Linkerd gives 504 gateway timeout and when I checked Linkerd logs I can see that it was still making requests to the old endpoints. (Not sure if this is a config issue). It get's fixed on its own after some time.

**What you expected to happen**:
Endpoints should be instantly updated whenever there is a deployment.

**How to reproduce it (as minimally and precisely as possible)**:
Rails Puma Server serving web pages and making requests to the service just after a deployment.

**Anything else we need to know?**:
Our router config:
```
    - protocol: http
      label: webapp-external
      identifier:
        kind: io.l5d.header.token
        header: Host
      interpreter:
        kind: io.l5d.namerd
        dst: /$/inet/namerd.linkerd.svc.cluster.local/4100
        namespace: external
        transformers:
        - kind: io.l5d.k8s.daemonset
          namespace: linkerd
          port: webapp-ingress
          service: linkerd-internal
      servers:
      - port: 4143
        ip: 0.0.0.0
      client:
        kind: io.l5d.global
        loadBalancer:
          kind: ewma
          enableProbation: false
          maxEffort: 5
          decayTimeMs: 10
        failureAccrual:
          kind: io.l5d.consecutiveFailures
          failures: 5
      service:
        kind: io.l5d.global

    - protocol: http
      label: webapp-ingress
      identifier:
        kind: io.l5d.header.token
        header: Host
      interpreter:
        kind: io.l5d.namerd
        dst: /$/inet/namerd.linkerd.svc.cluster.local/4100
        namespace: external
        transformers:
        - kind: io.l5d.k8s.localnode
      servers:
      - port: 4145
        ip: 0.0.0.0
      client:
        kind: io.l5d.global
        loadBalancer:
          kind: ewma
          enableProbation: false
          maxEffort: 5
          decayTimeMs: 10
        failureAccrual:
          kind: io.l5d.consecutiveFailures
          failures: 5
      service:
        kind: io.l5d.global
```

**Environment**:
- linkerd/namerd version, config files: 1.2.0/1.2.0
- Platform, version, and config files (Kubernetes, DC/OS, etc): Kubernetes
- Cloud provider or hardware configuration: AWS

**Comment by mejran** [comment]
We hit this issue as well, however out of two linkerd ingress controllers one updated correctly to the new endpoint and one still pointed to the old endpoint. Something to watch out for since the issue may be random or configuration dependent.

**Comment by wmorgan** [comment]
Thanks @kumudt, @mejran.  We'll take a look.

**Comment by hawkw** [comment]
Hi @mejran and @kumudt, this looks like the same issue as #1626 and #1635. We're trying to find the cause of this problem, and hopefully we'll have a fix soon.

Thanks for reporting!

**Comment by hawkw** [comment]
Hi again @kumudt and @mejran, just wanted to let you know that I've opened pull request #1638, which should fix this issue (and #1626 and #1635). We'll try and get the fix out to you as soon as possible!

**Comment by kumudt** [comment]
Any workaround for this until this PR gets merged??

**Comment by kumudt** [comment]
Today, we have found another issue along with this. It is not just for a single service. We have other services as well which are failing. Also, this time we didn't even do any deployments on those services which are failing. Later, we deleted all the Linkerd and Namerd pods which fixed it. This is also happening randomly.
Not sure, if your issues #1626 and #1635 explains this behavior.

**Comment by Taik** [comment]
@kumudt there's no real workaround AFAIK; doing a rolling delete of linkerd pod does it for us, but its not ideal.

**Comment by hawkw** [comment]
Hi @kumudt, in the meantime, you can try using the Docker image `buoyantio/linkerd:1.2.0.fix4-SNAPSHOT`, but please note this is not a production ready release yet.

**Comment by kumudt** [comment]
I deployed Linkerd and Namerd 1.2.1 and made a deployment to my application. It failed just like before with 504 and I see the exact same logs in the linkerd pods.


```
[l5d-cmlms l5d] E 0915 08:47:15.837 UTC THREAD44 TraceId:22097486f9419347: service failure: Failure(connection timed out: /100.96.3.244:3000 at remote address: /100.96.3.244:3000. Remote Info: Not Available, flags=0x09) with RemoteInfo -> Upstream Address: /100.96.3.241:37030, Upstream Client Id: Not Available, Downstream Address: /100.96.3.244:3000, Downstream Client Id: %/io.l5d.k8s.localnode/100.96.3.241/#/io.l5d.k8s/webapp/webapp-server/webapp-service, Trace Id: 22097486f9419347.e6fab0ca0856059c<:db5b9130907f941d 
[l5d-cmlms l5d] E 0915 08:47:16.478 UTC THREAD37 TraceId:22097486f9419347: service failure: Failure(request cancelled. Remote Info: Upstream Address: /10.11.10.139:21963, Upstream Client Id: Not Available, Downstream Address: /100.96.3.241:4145, Downstream Client Id: %/io.l5d.k8s.daemonset/linkerd/webapp-ingress/linkerd-internal/#/io.l5d.k8s/webapp/webapp-server/webapp-service, Trace Id: 22097486f9419347.37618bd902da6cc1<:22097486f9419347, flags=0x03) with RemoteInfo -> Upstream Address: /100.96.3.241:37030, Upstream Client Id: Not Available, Downstream Address: /100.96.3.244:3000, Downstream Client Id: %/io.l5d.k8s.localnode/100.96.3.241/#/io.l5d.k8s/webapp/webapp-server/webapp-service, Trace Id: 22097486f9419347.760c2ba7b873dab5<:37618bd902da6cc1 
[l5d-cmlms l5d] E 0915 08:47:16.479 UTC THREAD42 TraceId:22097486f9419347: service failure: com.twitter.finagle.CancelledRequestException: request cancelled. Remote Info: Upstream Address: /10.11.10.139:21963, Upstream Client Id: Not Available, Downstream Address: /100.96.3.241:4145, Downstream Client Id: %/io.l5d.k8s.daemonset/linkerd/webapp-ingress/linkerd-internal/#/io.l5d.k8s/webapp/webapp-server/webapp-service, Trace Id: 22097486f9419347.37618bd902da6cc1<:22097486f9419347 
```

**Comment by hawkw** [comment]
Hi @kumudt, that's disappointing to hear. Your deployments must be effected by another issue besides #1626. We'll keep looking into this.

**Comment by hawkw** [comment]
Could you possibly post the configuration file for Namerd as well?

**Comment by kumudt** [comment]
```
    telemetry:
    - kind: io.l5d.influxdb

    namers:
    - kind: io.l5d.k8s
      host: localhost
      port: 8001

    storage:
      kind: io.l5d.k8s
      host: localhost
      port: 8001
      namespace: linkerd

    interfaces:
    - kind: io.l5d.thriftNameInterpreter
      ip: 0.0.0.0
      port: 4100
    - kind: io.l5d.mesh
      ip: 0.0.0.0
      port: 4321
    - kind: io.l5d.httpController
      ip: 0.0.0.0
      port: 4180
```

**Comment by hawkw** [comment]
Thanks!

**Comment by hawkw** [comment]
Hi again @kumudt, I'm working on a reproduction for this issue, can I get you to give me an example of what steps you're using to deploy your application? I'm guessing it's `kubectl deploy`, but it would be nice to know exactly what you're doing. Thanks!

**Comment by kumudt** [comment]
I am using
```
kubectl apply -f <deployment-config-file>.yaml
```
This will create new pods and delete the old ones. Also, at the end of the deployment we are deleting the old replicaset.

**Comment by hawkw** [comment]
@kumudt, you've said you first observed this issue upon upgrading to Linkerd 1.2.0. Can you tell me what Linkerd version you were upgrading _from_?

**Comment by kumudt** [comment]
From 1.1.2. We skipped 1.1.3. Currently, we have downgraded it to 1.1.3.

**Comment by hawkw** [comment]
Are you still seeing this issue on 1.1.3?

**Comment by kumudt** [comment]
No. Haven't checked much after downgrading to 1.1.3. But, don't think so. We have seen it significantly in 1.2.0 and 1.2.1

**Comment by hawkw** [comment]
Hi @kumudt, I haven't been able to reproduce this issue with Linkerd 1.2.1 and Namerd 1.2.1. Here's my Linkerd configuration:
```yaml
    routers:
    - protocol: http
      label: outgoing
      identifier:
        kind: io.l5d.header.token
        header: Host
      interpreter:
        kind: io.l5d.namerd
        dst: /$/inet/namerd.liza.svc.cluster.local/4100
        namespace: internal
        transformers:
        - kind: io.l5d.k8s.daemonset
          namespace: liza
          port: incoming
          service: l5d
      servers:
      - port: 4140
        ip: 0.0.0.0
      client:
        kind: io.l5d.global
        loadBalancer:
          kind: ewma
          enableProbation: false
          maxEffort: 5
          decayTimeMs: 10
        failureAccrual:
          kind: io.l5d.consecutiveFailures
          failures: 5
      service:
        kind: io.l5d.global

    - protocol: http
      label: incoming
      identifier:
        kind: io.l5d.header.token
        header: Host
      interpreter:
        kind: io.l5d.namerd
        dst: /$/inet/namerd.liza.svc.cluster.local/4100
        namespace: internal
        transformers:
        - kind: io.l5d.k8s.localnode
      servers:
      - port: 4141
        ip: 0.0.0.0
      client:
        kind: io.l5d.global
        loadBalancer:
          kind: ewma
          enableProbation: false
          maxEffort: 5
          decayTimeMs: 10
        failureAccrual:
          kind: io.l5d.consecutiveFailures
          failures: 5
      service:
        kind: io.l5d.global

    - protocol: http
      label: external
      interpreter:
        kind: io.l5d.namerd
        dst: /$/inet/namerd.liza.svc.cluster.local/4100
        namespace: external
      servers:
      - port: 4142
        ip: 0.0.0.0
      client:
        kind: io.l5d.global
        loadBalancer:
          kind: ewma
          enableProbation: false
          maxEffort: 5
          decayTimeMs: 10
        failureAccrual:
          kind: io.l5d.consecutiveFailures
          failures: 5
      service:
        kind: io.l5d.global
```
and my Namerd configuration is
```yaml
    namers:
    - kind: io.l5d.k8s
      experimental: true
      host: localhost
      port: 8001

    storage:
      kind: io.l5d.k8s
      host: localhost
      port: 8001
      namespace: default

    interfaces:
    - kind: io.l5d.thriftNameInterpreter
      ip: 0.0.0.0
      port: 4100
    - kind: io.l5d.httpController
      ip: 0.0.0.0
      port: 4180
```

I've taken the following steps to reproduce:

1. deployed Linkerd and Namerd with `kubectl -n liza apply -f`
2. deploy the `hello` and `world` services with `kubectl -n liza apply -f hello_world.yml`
3. `curl -H 'Host: hello' -s $L5D_INGRESS_LB:4140`, Linkerd routes correctly to the `hello` and `world` services, as expected
4. change the image versions in the config file for the `hello` and `world` to ensure they will be redeployed
5. deploy again with `kubectl -n liza apply -f hello_world.yml`
6. `curl -H 'Host: hello' -s $L5D_INGRESS_LB:4140` / `curl -H 'Host: world' -s $L5D_INGRESS_LB:4140`
7. Linkerd routes correctly to the new endpoints, and I don't see any error messages in the logs

I've repeated the deployment a few times, and I'm still not seeing any problems.

Please let me know if there's something I'm missing, I've tried to match your configuration as closely as possible.
