### ISSUE TITLE
namerd needs an alternative to the deprecated k8s ThirdPartyResource

### ISSUE THREAD

**Issue by ljmatkins** [linkerd/linkerd#1661]
Kubernetes 1.7 has deprecated ThirdPartyResources in favor of CustomResourceDefinitions, and TPRs are no longer supported in Kubernetes 1.8. This will break namerd on k8s 1.8.

**Comment by esbie** [comment]
related to https://github.com/linkerd/linkerd-examples/issues/183

**Comment by zsojma** [comment]
Hello, is there any update on this issue? Thank you.

**Comment by siggy** [comment]
Let's ensure we have integration tests in place prior to making changes.

**Comment by wmorgan** [comment]
@zsojma we should be taking a look at this this week

**Comment by zsojma** [comment]
I followed kubernetes instructions how to migrate a ThirdPartyResource on this link: [https://kubernetes.io/docs/tasks/access-kubernetes-api/migrate-third-party-resource/](url) and it looks like it is working.

Here is my result:
```
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: dtabs.l5d.io
spec:
  scope: Namespaced
  group: l5d.io
  version: v1alpha1
  names:
    kind: DTab
    plural: dtabs
    singular: dtab
```
