### ISSUE TITLE
Thrift protocol: incorrect `thriftMethodInDst` behavior when using TThrift

### ISSUE THREAD

**Issue by mirosval** [linkerd/linkerd#1662]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:

I get an exception `org.apache.thrift.TApplicationException: Internal error processing deleteImage: 'com.twitter.finagle.NoBrokersAvailableException: No hosts are available for /svc/deleteImage, Dtab.base=[/consul=>/#/io.l5d.consul/small-virtualbox;/svc=>/consul], Dtab.local=[]. Remote Info: Not Available'` when I attempt to call my Thrift service.

As you can see, the dentry being resolved is `/svc/deleteImage`, `deleteImage` is a method.

**What you expected to happen**:

According to the documentation [here](https://linkerd.io/config/1.2.1/linkerd/index.html#thrift-protocol) the format should be `/ dstPrefix [/ dest] [/ thriftMethod ] ` but there is nothing in the `dest` segment. I am using Finagle 7.1.0 to construct my client like so:

```scala
new ImageService.FinagledClient(
  Thrift.client
    .withAttemptTTwitterUpgrade
    .newClient(thriftAddress, "image_service_client")
    .toService
)
```

Linkerd 1.2.1 config
```yaml
admin:
  ip: 0.0.0.0
  port: 9990

namers:
- kind: io.l5d.consul
  includeTag: false
  useHealthCheck: false
  setHost: true

routers:
- protocol: http
  label: http
  service:
    responseClassifier:
      kind: io.l5d.http.retryableIdempotent5XX
  identifier:
   kind: io.l5d.methodAndHost
  dtab: |
    /consul => /#/io.l5d.consul/small-virtualbox;
    /local-consul => /$/io.buoyant.http.subdomainOfPfx/service.consul/consul;
    /named-consul => /$/io.buoyant.http.subdomainOfPfx/service.small-virtualbox.consul/consul;
    /svc/*/* => /local-consul | /named-consul;
  servers:
  - port: 80
    ip: 0.0.0.0
  client:
   requeueBudget:
     percentCanRetry: 5.0
- protocol: thrift
  experimental: true
  label: thrift
  dtab: |
    /consul => /#/io.l5d.consul/small-virtualbox;
    /svc => /consul;
  thriftProtocol: binary
  thriftMethodInDst: true
  servers:
  - port: 81
    ip: 0.0.0.0
    thriftFramed: true
  client:
    thriftFramed: true
    attemptTTwitterUpgrade: true
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

* HTTP configuration works without problems
* I have tried also ThriftMux on the client and in Linkerd, to no avail
* There is nothing in the logs for thrift, I only get the exception on the client side
