### ISSUE TITLE
Undesired Warning in namerd output when consul observation is released

### ISSUE THREAD

**Issue by edio** [linkerd/linkerd#1670]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
After upgrade to namerd 1.3.0 there are warnings in namerd output
```
W 1011 15:35:08.872 UTC THREAD41 TraceId:5fbf736f9b6f2da2: consul datacenter 'bethesda-dev' service 'namerd-grpc' observation error Failure(service observation released, flags=0x02) with RemoteInfo -> Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /127.0.0.1:8500, Downstream label: client, Trace Id: 4b87215a3717cc59.4b87215a3717cc59<:4b87215a3717cc59, falling back to last good state
```

**How to reproduce it (as minimally and precisely as possible)**:
Resolving any service via namerd with consul namer
```
$ curl 'http://namerd-instance:4180/api/1/resolve/default?path=/consul/someservice
```
```
admin:
  ip: 127.0.0.1
  port: 9001
namers:
- kind: io.l5d.consul
  experimental: true
  host: 127.0.0.1
  port: 8500
  setHost: true
  useHealthCheck: true
  consistencyMode: stale
  failFast: false
  prefix: /consul
interfaces:
- kind: io.l5d.httpController
  ip: 127.0.0.1
  port: 4180
```

**Environment**:
namerd v1.3.0
consul v0.9.3
