### ISSUE TITLE
OutOfDirectMemoryError errors causing linkerd to fail

### ISSUE THREAD

**Issue by DukeyToo** [linkerd/linkerd#1690]
Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:
Over a period of days, linkerd memory usage climbs until it reaches a maximum and starts throwing OutOfDirectMemoryError errors

**What you expected to happen**:
OutOfDirectMemoryError errors should not happen

**How to reproduce it (as minimally and precisely as possible)**:
Running linkerd 1.3.0 single instance per host, with namerd on separate hosts.  Environment memory overrides: `JVM_HEAP_MAX=1024M` and `JVM_HEAP_MIN=1024M`.  Let run for days, and monitor process memory usage.  Usage increases until errors start occuring:

Memory usage chart (10/27 new VMs running 1.3.0, dips at the end are me restarting linkerd):
<img width="1368" alt="screen shot 2017-11-01 at 10 56 02 am" src="https://user-images.githubusercontent.com/1268000/32284955-e378ae2e-bef6-11e7-958b-7118cf86a197.png">

Stack trace:
```
linkerd[2410]: W 1101 14:10:26.714 UTC THREAD42: Unhandled exception in connection with /10.49.154.23:42176, shutting down connection
linkerd[2410]: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 1048576 byte(s) of direct memory (used: 1037041958, max: 1037959168)
linkerd[2410]: at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:618)
linkerd[2410]: at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:572)
linkerd[2410]: at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
linkerd[2410]: at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
linkerd[2410]: at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
linkerd[2410]: at io.netty.buffer.PoolArena.allocate(PoolArena.java:214)
linkerd[2410]: at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
linkerd[2410]: at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
linkerd[2410]: at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:181)
linkerd[2410]: at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:172)
linkerd[2410]: at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:133)
linkerd[2410]: at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:80)
linkerd[2410]: at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:122)
linkerd[2410]: at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
linkerd[2410]: at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
linkerd[2410]: at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
linkerd[2410]: at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
linkerd[2410]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
linkerd[2410]: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
linkerd[2410]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
linkerd[2410]: at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23)
linkerd[2410]: at java.lang.Thread.run(Unknown Source)
```

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files:
1.3.0 linkerd and namerd.  linkerd config:
```
admin:
  port: 9990
  ip: 0.0.0.0
routers:
- protocol: http
  label: microservices_prod
  dstPrefix: /http
  interpreter:
    kind: io.l5d.mesh
    dst: /$/inet/cwl-mesos-masters.service.consul/4182
    experimental: true
    root: /microservices-prod
  identifier:
    - kind: io.l5d.path
      segments: 3
    - kind: io.l5d.path
      segments: 2
    - kind: io.l5d.path
      segments: 1
  servers:
  - port: 4170
    ip: 0.0.0.0
  client:
    kind: io.l5d.global
    loadBalancer:
      kind: ewma
    failureAccrual:
      kind: io.l5d.consecutiveFailures
      failures: 5
    requeueBudget:
      minRetriesPerSec: 10
      percentCanRetry: 0.2
      ttlSecs: 10
  service:
    kind: io.l5d.global
    totalTimeoutMs: 10000
    responseClassifier:
      kind: io.l5d.http.retryableRead5XX
    retries:
      budget:
        minRetriesPerSec: 10
        percentCanRetry: 0.2
        ttlSecs: 10
- protocol: http
  label: proxy_by_host
  dstPrefix: /http
  interpreter:
    kind: io.l5d.mesh
    dst: /$/inet/cwl-mesos-masters.service.consul/4182
    experimental: true
    root: /default
  identifier:
    - kind: io.l5d.header.token
      header: Host
  servers:
  - port: 4141
    ip: 0.0.0.0
  - port: 80
    ip: 0.0.0.0
- protocol: http
  label: proxy_by_path3
  dstPrefix: /http
  interpreter:
    kind: io.l5d.mesh
    dst: /$/inet/cwl-mesos-masters.service.consul/4182
    experimental: true
    root: /default
  identifier:
    - kind: io.l5d.path
      segments: 3
  servers:
  - port: 4153
    ip: 0.0.0.0
- protocol: http
  label: proxy_by_path2
  dstPrefix: /http
  interpreter:
    kind: io.l5d.mesh
    dst: /$/inet/cwl-mesos-masters.service.consul/4182
    experimental: true
    root: /default
  identifier:
    - kind: io.l5d.path
      segments: 2
  servers:
  - port: 4152
    ip: 0.0.0.0
- protocol: http
  label: proxy_by_path1
  dstPrefix: /http
  interpreter:
    kind: io.l5d.mesh
    dst: /$/inet/cwl-mesos-masters.service.consul/4182
    experimental: true
    root: /default
  identifier:
    - kind: io.l5d.path
      segments: 1
  servers:
  - port: 4151
    ip: 0.0.0.0
telemetry:
- kind: io.l5d.influxdb
```

- Platform, version, and config files (Kubernetes, DC/OS, etc):
CentOS Linux release 7.4.1708 (Core) 

- Cloud provider or hardware configuration:
Google Cloud

**Comment by siggy** [comment]
Thanks for the detailed report @DukeyToo, we are investigating this.

**Comment by amitsaha** [comment]
hi @DukeyToo do you mind sharing the specific metric you are tracking for the memory usage? Thanks :)

**Comment by zackangelo** [comment]
@DukeyToo can you share how many CPUs are on the linkerd hosts?

**Comment by DukeyToo** [comment]
@zackangelo there are 8 cpu cores on the hosts.  @amitsaha we're analyzing `/proc` data on linux, RSS memory only (using https://github.com/influxdata/telegraf/tree/master/plugins/inputs/procstat).

**Comment by siggy** [comment]
Quick update for folks watching this issue. We have reproduced a leak and are actively working on a fix. To confirm the leak you are seeing is the same one we have identified, have a look at your `open_streams` metrics. If they grow over time, that is the leak.

**Comment by amitsaha** [comment]
Hi @siggy thanks, which specific metric is this? I tried searching in the prometheus exported metrics, but can't seem to find it?

**Comment by amitsaha** [comment]
Thanks @DukeyToo

**Comment by zackangelo** [comment]
@DukeyToo are you seeing this exception in your linkerd logs? 
```
Nov 03 17:36:55  WARN 1103 17:36:55.421 CDT finagle/netty4-6: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
Nov 03 17:36:55  java.io.IOException: Connection reset by peer
Nov 03 17:36:55  at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
Nov 03 17:36:55  at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
Nov 03 17:36:55  at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
Nov 03 17:36:55  at sun.nio.ch.IOUtil.read(IOUtil.java:192)
```

**Comment by DukeyToo** [comment]
@zackangelo no, I cannot find that error in our logs

**Comment by siggy** [comment]
@amitsaha We're looking for any metric ending in `open_streams`.

For example:
- `rt:client:stream:open_streams`
- `rt:server:stream:open_streams`
- `rt:io_l5d_mesh:stream:open_streams`

**Comment by siggy** [comment]
Quick update: we are still actively investigating this. We believe it may be related to our usage of netty, in relation to reference counting, see http://netty.io/wiki/reference-counted-objects.html for more details.

To get additional information, if folks can try setting the environment variable `LOCAL_JVM_OPTIONS` to `-Dio.netty.leakDetection.level=paranoid -Dio.netty.leakDetection.maxRecords=500`, it should give us additional information around the nature of this leak.

**Comment by siggy** [comment]
@DukeyToo We have a fix up at: https://github.com/linkerd/linkerd/pull/1711 Is it possible to test this branch against your use case?

**Comment by DukeyToo** [comment]
@siggy sure, I will try

**Comment by hawkw** [comment]
Hi @DukeyToo, I just wanted to let you know that you can now test a release candidate for 1.3.3 by using the `buoyantio/linkerd:1.3.3-RC1-jdk` Docker image, which should make testing your use case against the fix much easier.

**Comment by DukeyToo** [comment]
@siggy @hawkw I took a build from master at https://github.com/linkerd/linkerd/tree/c6f0d2eaeecca80c60314e6f6cb852a31870877a but was unable to reproduce in our test environment, because it takes more than 24 hours of traffic until I can see the issue occurring - and our test environment linkerd instances are restarted every day by an automated process.

I did plot `rt:io_l5d_mesh:stream:open_streams` over time for various routers in test environment, and it does trend upward over time each day - so if the bug is indicated by gradual increases in that metric, then it is not seem like it is fixed for me.

Example (the drops are due to instances restarting as-scheduled): 
<img width="1372" alt="screen shot 2017-12-05 at 1 15 48 pm" src="https://user-images.githubusercontent.com/1268000/33625818-77cd695c-d9be-11e7-925a-89947e957d7a.png">

I also looked for `rt:client:stream:open_streams` and `rt:server:stream:open_streams` in /admin/metrics.json, but did not find those as metrics.

**Comment by hawkw** [comment]
Hi @DukeyToo, the gradual increase in `rt:{client, server}: stream:open_streams` metric is a symptom of an unrelated issue that only affects HTTP/2 routers, which track those metrics. As your configuration doesn't contain any H2 routers,  it's correct for you not to see those metrics, since HTTP/1.1 is not a streaming protocol. I believe @siggy was mistaken when he told you to look at that metric. Sorry for any confusion!

**Comment by DukeyToo** [comment]
I have captured some logs with `LOCAL_JVM_OPTIONS=-Dio.netty.leakDetection.level=paranoid -Dio.netty.leakDetection.maxRecords=500` at https://gist.github.com/DukeyToo/582285e2b3603ce9468e4f2c2f21be75

**Comment by siggy** [comment]
Thanks for the log @DukeyToo. Can you confirm what version of linkerd this was with?

**Comment by hawkw** [comment]
@siggy, I believe [in the logs](https://gist.github.com/DukeyToo/582285e2b3603ce9468e4f2c2f21be75#file-linkerd-log-L8) that @DukeyToo posted, the Linkerd reports itself as `linkerd 1.3.2-SNAPSHOT`. A few comments ago (https://gist.github.com/DukeyToo/582285e2b3603ce9468e4f2c2f21be75#file-linkerd-log-L8) @DukeyToo says he did a build of master as of revision c6f0d2eaeecca80c60314e6f6cb852a31870877a, I'm assuming that's what he's running currently?

**Comment by DukeyToo** [comment]
Yes, that is correct

**Comment by hawkw** [comment]
Hi @DukeyToo, following up on this issue: we've fixed a number of memory leaks since the version where this issue was observed. Are you still seeing this leak in the latest release, Linkerd 1.3.4?

**Comment by chrismikehogan** [comment]
FWIW, we were seeing similar issues to @DukeyToo. We deployed 1.3.5 and the leak we were seeing was resolved.

**Comment by wmorgan** [comment]
@chrismikehogan thanks! @DukeyToo, it would be great to have you try 1.3.4 or 1.3.5.

**Comment by DukeyToo** [comment]
I am busy testing 1.3.4.  It takes a few days to reproduce, so I'm hoping for the best at this stage.  Should know soon.

**Comment by wmorgan** [comment]
Thank you! Standing by eagerly.

**Comment by DukeyToo** [comment]
I restarted linkerd this afternoon, before it reached the memory usage where we have seen this issue in the past ... so it will be a while longer before I know if it still happens. 

If nothing else, it seems to be taking longer to get to the memory usage threshold where the bug occurred :)

**Comment by hawkw** [comment]
That, at least, is good to hear!

**Comment by DukeyToo** [comment]
This is not fixed.  Took 5 days to reproduce, but it happened again.

Let me know if you need any more info.  Metrics are logged to an InfluxDb so I can post whatever we gather that might be relevant.

**Comment by wmorgan** [comment]
Bummer. We're going to allocate some time to dig into this later this month.

**Comment by mebe** [comment]
We've run into something that looks identical. We are running Linkerd in front of an object storage system, and are blocked by this issue. We get `io.netty.util.internal.OutOfDirectMemoryError` with an identical stacktrace after we've uploaded around 400-500 GB of data. We're running the Linkerd with `-Xms` and `-Xmx` of 4 GB and `-XX:MaxDirectMemorySize` of 2GB.

This is fairly straightforward to reproduce by running Minio in Docker and using the AWS CLI to repeatedly upload and delete stuff.

Let's start by bringing up the Minio container:

```
docker pull minio/minio
docker run -p 9000:9000 minio/minio server /data
```

Make a note of the AccessKey and SecretKey printed by this. You'll need those later.

Install AWS CLI, e.g. with the bundled installer:

```
curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
unzip awscli-bundle.zip
./awscli-bundle/install -b ~/bin/aws
```

Configure AWS CLI to use Minio:

```
mkdir ~/.aws

cat > ~/.aws/config <<EOF
[default]
s3 =
    max_concurrent_request = 100
    endpoint_url = http://minio
    multipart_threshold = 50MB
    multipart_chunksize = 10MB
EOF

cat > ~/.aws/credentials <<EOF
[default]
aws_access_key_id = <THE-ACCESS-KEY-FROM-MINIO-HERE>
aws_secret_access_key = <THE-SECRET-KEY-FROM-MINIO-HERE>
EOF
```

Configure Linkerd to proxy to Minio:

```
cat > linkerd-minio.yaml <<EOF
admin:
  port: 9990

routers:
- protocol: http
  dtab: |
    /svc/minio => /$/inet/127.0.0.1/6060;
  httpAccessLog: logs/access.log
  maxRequestKB: 51200
  maxResponseKB: 51200
  servers:
  - port: 6007
    ip: 127.0.0.1
EOF
```

Start Linkerd:

```
LOCAL_JVM_OPTIONS="-XX:MaxDirectMemorySize=2G" JVM_HEAP_MIN=4G JVM_HEAP_MAX=4G linkerd linkerd-minio.yaml
```

Make AWS CLI use Linkerd as a proxy:

```
export HTTP_PROXY=http://127.0.0.1:6007
```

Create a bucket in Minio:

```
~/bin/aws s3 mb s3://five-gigs
```

Create some files to upload:

```
mkdir five-gigs; touch five-gigs/5gb-{1..10} && shred -n 1 -s 5G five-gigs/5gb-{1..10}
```

Loop upload and delete until it fails:

```
until [ $? -gt 0 ]; do ~/bin/aws s3 rm --recursive s3://five-gigs/ && ~/bin/aws s3 sync five-gigs s3://five-gigs; done
```

After about 400-500 GB (which takes a bit over an half an hour for me), you should start seeing `OutOfDirectMemoryError`s from Linkerd and the sync will fail. Linkerd won't recover from this until it's restarted.

I imagine the reproduction time will be shorter with less `-XX:MaxDirectMemorySize`. With 4 GB heap, the heap usage doesn't seem to be a problem and total GC for the whole run stays in a couple of seconds.

I hope this helps! Let me know if you need any more information.
