### ISSUE TITLE
PathIdentifier consumes a segment of the path with query parameters

### ISSUE THREAD

**Issue by ievgen-kolomiiets** [linkerd/linkerd#1725]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
`PathIdentifier` consumes a segment of the path with query parameters.

**What you expected to happen**:
Expect query parameters to remain in the query

**How to reproduce it (as minimally and precisely as possible)**:
I have:
1. dtab record `/svc/play => /#/io.l5d.k8s/namespace/http/play-service`. 
1. Service in Kubernetes that handles requests under the `/`.
1. Linkerd with `PathIdentifier`
    ```
        identifier:
          - kind: io.l5d.path
            segments: 1
            consume: true
    ```

So when I query service with url `/play?param=value` query parameters don't come to the service. But when I query `/play/?param=value` everything works well.
