### ISSUE TITLE
Linkerd checking Consul for nonexistent Services

### ISSUE THREAD

**Issue by pcalcado** [linkerd/linkerd#1766]
## Filing a Linkerd issue ##

Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:

@yangzhares reports in [#1670](https://github.com/linkerd/linkerd/issues/1670#issuecomment-354936937): 

> -------------------------------------------------------------------------------------------
On my environment i got this issue again, every 5 mins namerd will check service health status info from Consul, but in fact those services are not existed.
Namerd and linkerd: 1.3.4
Namerd logs:
```
E 0103 01:32:44.061 UTC THREAD30: Retrying Consul request 'GET /v1/health/service/phpnuke73?index=1082854&dc=hf01&tag=active&passing=true' on NonFatal error: com.twitter.finagle.ChannelWriteException: com.twitter.finagle.ChannelClosedException: null at remote address: /127.0.0.1:8500. Remote Info: Not Available from service: client. Remote Info: Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /127.0.0.1:8500, Downstream label: client, Trace Id: 46d8dd952ddb6102.46d8dd952ddb6102<:46d8dd952ddb6102
E 0103 01:32:44.064 UTC THREAD33: Retrying Consul request 'GET /v1/health/service/webboard?index=1082854&dc=hf01&tag=active&passing=true' on NonFatal error: com.twitter.finagle.ChannelWriteException: com.twitter.finagle.ChannelClosedException: null at remote address: /127.0.0.1:8500. Remote Info: Not Available from service: client. Remote Info: Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /127.0.0.1:8500, Downstream label: client, Trace Id: e3bad8c27cd3b046.e3bad8c27cd3b046<:e3bad8c27cd3b046
E 0103 01:32:44.069 UTC THREAD32: Retrying Consul request 'GET /v1/health/service/owls?index=1082854&dc=hf01&tag=active&passing=true' on NonFatal error: com.twitter.finagle.ChannelWriteException: com.twitter.finagle.ChannelClosedException: null at remote address: /127.0.0.1:8500. Remote Info: Not Available from service: client. Remote Info: Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /127.0.0.1:8500, Downstream label: client, Trace Id: 871b1a26d5186be5.871b1a26d5186be5<:871b1a26d5186be5
E 0103 01:32:44.077 UTC THREAD35: Retrying Consul request 'GET /v1/health/service/mt?index=1082854&dc=hf01&tag=active&passing=true' on NonFatal error: com.twitter.finagle.ChannelWriteException: com.twitter.finagle.ChannelClosedException: null at remote address: /127.0.0.1:8500. Remote Info: Not Available from service: client. Remote Info: Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /127.0.0.1:8500, Downstream label: client, Trace Id: b2b7b1825a8091c1.b2b7b1825a8091c1<:b2b7b1825a8091c1
W 0103 01:32:44.078 UTC THREAD35 TraceId:e2e304cd6c60297f: consul datacenter 'hf01' service 'versatilebulletinboard' observation error Failure(service observation released, flags=0x02) with RemoteInfo -> Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /127.0.0.1:8500, Downstream label: client, Trace Id: c1e8fde74c62d5b7.c1e8fde74c62d5b7<:c1e8fde74c62d5b7 with Service -> client, falling back to last good state
E 0103 01:32:44.081 UTC THREAD34: Retrying Consul request 'GET /v1/health/service/mt?index=1082854&dc=hf01&tag=active&passing=true' on NonFatal error: com.twitter.finagle.ChannelWriteException: com.twitter.finagle.ChannelClosedException: null at remote address: /127.0.0.1:8500. Remote Info: Not Available from service: client. Remote Info: Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /127.0.0.1:8500, Downstream label: client, Trace Id: aeea482ab304669a.aeea482ab304669a<:aeea482ab304669a
W 0103 01:32:44.091 UTC THREAD35 TraceId:e2e304cd6c60297f: consul datacenter 'hf01' service 'thatware_0.4.6' observation error Failure(service observation released, flags=0x02) with RemoteInfo -> Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /127.0.0.1:8500, Downstream label: client, Trace Id: 8efa41401a627d36.8efa41401a627d36<:8efa41401a627d36 with Service -> client, falling back to last good state
E 0103 01:32:44.099 UTC THREAD29: Retrying Consul request 'GET /v1/health/service/mt?index=1082854&dc=hf01&tag=active&passing=true' on NonFatal error: com.twitter.finagle.ChannelWriteException: com.twitter.finagle.ChannelClosedException: null at remote address: /127.0.0.1:8500. Remote Info: Not Available from service: client. Remote Info: Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /127.0.0.1:8500, Downstream label: client, Trace Id: a250cc973acfbfeb.a250cc973acfbfeb<:a250cc973acfbfeb
E 0103 01:32:44.103 UTC THREAD21: Retrying Consul request 'GET /v1/health/service/mt?index=1082854&dc=hf01&tag=active&passing=true' on NonFatal error: com.twitter.finagle.ChannelWriteException: com.twitter.finagle.ChannelClosedException: null at remote address: /127.0.0.1:8500. Remote Info: Not Available from service: client. Remote Info: Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /127.0.0.1:8500, Downstream label: client, Trace Id: e650cff757b92f83.e650cff757b92f83<:e650cff757b92f83
E 0103 01:32:44.142 UTC THREAD33: Retrying Consul request 'GET /v1/health/service/mt?index=1082854&dc=hf01&tag=active&passing=true' on NonFatal error: com.twitter.finagle.ChannelWriteException: com.twitter.finagle.ChannelClosedException: null at remote address: /127.0.0.1:8500. Remote Info: Not Available from service: client. Remote Info: Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /127.0.0.1:8500, Downstream label: client, Trace Id: 370a10407a3c32f5.370a10407a3c32f5<:370a10407a3c32f5
W 0103 01:32:44.145 UTC THREAD33 TraceId:e2e304cd6c60297f: consul datacenter 'hf01' service 'phpware' observation error Failure(service observation released, flags=0x02) with RemoteInfo -> Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /127.0.0.1:8500, Downstream label: client, Trace Id: 52f79738bc990a36.52f79738bc990a36<:52f79738bc990a36 with Service -> client, falling back to last good state
E 0103 01:32:44.148 UTC THREAD30: Retrying Consul request 'GET /v1/health/service/backofficelite?index=1083373&dc=hf01&tag=active&passing=true' on NonFatal error: com.twitter.finagle.ChannelWriteException: com.twitter.finagle.ChannelClosedException: null at remote address: /127.0.0.1:8500. Remote Info: Not Available from service: client. Remote Info: Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /127.0.0.1:8500, Downstream label: client, Trace Id: 64259cb64ae21831.64259cb64ae21831<:64259cb64ae21831
W 0103 01:32:44.162 UTC THREAD27 TraceId:e2e304cd6c60297f: consul datacenter 'hf01' service 'phpnuke73' observation error Failure(service observation released, flags=0x02) with RemoteInfo -> Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /127.0.0.1:8500, Downstream label: client, Trace Id: d04a4f922611f366.d04a4f922611f366<:d04a4f922611f366 with Service -> client, falling back to last good state
W 0103 01:32:44.180 UTC THREAD33 TraceId:e2e304cd6c60297f: consul datacenter 'hf01' service 'espocrm' observation error Failure(service observation released, flags=0x02) with RemoteInfo -> Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /127.0.0.1:8500, Downstream label: client, Trace Id: 44d1b83ca1fb3901.44d1b83ca1fb3901<:44d1b83ca1fb3901 with Service -> client, falling back to last good state
W 0103 01:32:44.210 UTC THREAD21 TraceId:e2e304cd6c60297f: consul datacenter 'hf01' service 'owls' observation error Failure(service observation released, flags=0x02) with RemoteInfo -> Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /127.0.0.1:8500, Downstream label: client, Trace Id: d9c3d2738d7fb40b.d9c3d2738d7fb40b<:d9c3d2738d7fb40b with Service -> client, falling back to last good state
```
Grafana graph for RPC reqeust number received by Consul server:
<img width="1407" alt="consul-graph" src="https://user-images.githubusercontent.com/6067833/34509702-138c265a-f088-11e7-9b69-a01622785da0.png">
  > -------------------------------------------------------------------------------------------

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files:
- Platform, version, and config files (Kubernetes, DC/OS, etc):
- Cloud provider or hardware configuration:

**Comment by yangzhares** [comment]
@pcalcado , thank you for checking this, if you need more info, i help help you

**Comment by deebo91** [comment]
@yangzhares I am curious to see your linkerd configuration. Do you mind sharing your linkerd config so we get more insight as to what could be causing the issue?

**Comment by yangzhares** [comment]
linkerd config:
```
admin:
  port: 9990
  ip: 0.0.0.0

routers:
- protocol: http
  identifier:
    kind: io.l5d.custIdentifier
  label: cust_outgoing
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd.service.consul/4100
    namespace: cust
  servers:
  - port: 8080
    ip: 0.0.0.0
- protocol: http
  label: outgoing
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd.service.consul/4100
    namespace: default
  #httpAccessLog: /alloc/logs/access_outgoing.log
  servers:
  - port: 8081
    ip: 0.0.0.0

telemetry:
- kind: io.l5d.recentRequests
  sampleRate: 1.0
- kind: io.l5d.prometheus

usage:
  enabled: false
```

namerd config:
```
admin:
  ip: 0.0.0.0
  port: 9991

storage:
  kind: io.l5d.consul
  host: 127.0.0.1
  port: 8500
  pathPrefix: /namerd/dtabs
  datacenter: hf01
namers:
- kind: io.l5d.consul
  prefix: /io.l5d.consul
  host: 127.0.0.1
  port: 8500
  includeTag: false
  setHost: false
  useHealthCheck: true
- kind: io.l5d.consul
  prefix: /io.l5d.mbs.consul
  host: 127.0.0.1
  port: 8500
  includeTag: true
  setHost: false
  useHealthCheck: true
interfaces:
- kind: io.l5d.thriftNameInterpreter
  ip: 0.0.0.0
  port: 4100
- kind: io.l5d.httpController
  ip: 0.0.0.0
  port: 4180
```

dtab for namespace `cust`:
```
/active      => /#/io.l5d.mbs.consul/hf01/active;
/baking      => /#/io.l5d.mbs.consul/hf01/baking;
/svc/active  => /active;
/svc/baking  => /baking;
```
Some background for `io.l5d.custIdentifier`:
Identifier `io.l5d.custIdentifier` transforms request URL's first segment as service name, also reads HEADER from request to indicate a service is `active` or `baking`, be default, `active` , so,  GET http://example.com/app, will be transformed as `/svc/active/app`.
