### ISSUE TITLE
Linkerd fails to recognize k8s DELETED events

### ISSUE THREAD

**Issue by pavel-mikhalchuk** [linkerd/linkerd#1791]
Issue Type:

- [X] Bug report

**What happened**:

After ingress is deleted Linkerd still routes to the backend service.

**What you expected to happen**:

Linkerd should display this:

```
curl -H "Host: aservice.p.m.in.in.alutech24.com" localhost:3142
Unknown destination: Request("GET /", from /127.0.0.1:46336) / no ingress rule matches...
```

**How to reproduce it (as minimally and precisely as possible)**:

Ingress resources used:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aservice-l5d-pm-test
  annotations:
    kubernetes.io/ingress.class: "linkerd-dev"
spec:
  rules:
  - host: aservice.p.m.in.in.alutech24.com
    http:
      paths:
      - path:
        backend:
          serviceName: aservice
          servicePort: http
```

1. Create ingress resource
2. Delete ingress resource

**Anything else we need to know?**:

Sometimes it works instantly (as I'm expecting) and sometime it doesn't. Most times it doesn't. However after 40 minutes now Linkerd responds with "no ingress rule matches...".

Also yesterday when I deleted some of my ingress resources I've lost all of them in Linkerd. It started responding with "no ingress rule matches..." for all of my ingresses. I'm not 100% sure that it happened due to deletion of one of my ingresses but it happened. Linkerd restart helped and everything is back to normal. I'm currently investigating what happened and maybe come up with another issue about that. 

**Environment**:
- linkerd/namerd version, config files: Linkerd version - 1.3.5, config file - https://gist.github.com/pavel-mikhalchuk/5456e28e4dd7e958280e459b0ced0381
- Platform, version, and config files (Kubernetes, DC/OS, etc): Kubernetes 1.8 created with kubeadm (https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/); RBAC config - https://gist.github.com/pavel-mikhalchuk/1e52278f62ea76fcab423976e1524ed1
- Cloud provider or hardware configuration: Private DC; Ubuntu 16.04.3 xenial

**Linkerd logs**:

https://gist.github.com/pavel-mikhalchuk/3698ef093a67e41018fe1306fb31e604

Please let me know if you need more details.

Thanks!
