### ISSUE TITLE
Access log of different router mixed up together

### ISSUE THREAD

**Issue by leozc** [linkerd/linkerd#1808]
Issue Type:

- [X ] Bug report
- [ ] Feature request

**What happened**:
In our production setting, l5d has two router, one for **ingress** (to app in the same box) and one for **egress**
```
routers:
- protocol: http
  label: svc_egress
  httpAccessLog: /mnt/log/linkerd_outgoing_access.log
  servers:
  - port: 4140
    ip: 0.0.0.0
.... other lines here ...

- protocol: http
  label: svc_ingress
  httpAccessLog: /mnt/log/linkerd_incoming_access.log
  servers:
  - port: 4141
    ip: 0.0.0.0
.... other lines here ...
```

When a request comes into port 4141, I would expect access log goes into _linkerd_incoming_access.log_ but the reality is the entry shows up in _linkerd_outgoing_access.log_

**What you expected to happen**:
Access log goes to _linkerd_outgoing_access.log_

**How to reproduce it (as minimally and precisely as possible)**:
curl localhost:4141/foo/bar 

**Anything else we need to know?**:
L5d 1.3.4

**Environment**:
AWS EC2 box and L5D 1.3.4
