### ISSUE TITLE
Disabling TLS per static client configuration

### ISSUE THREAD

**Issue by hynek** [linkerd/linkerd#1845]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:

I’m trying to have TLS by default and disable it for certain clients:

```yaml
    client:
      kind: io.l5d.static
      configs:
        - prefix: /
          tls:
            # ...
        - prefix: /#/io.l5d.consul/.local/env-*/cdn
           tls: null
```

But it looks like a negative override doesn’t work: the requests are still https-based.

I’m getting a match, because if I set `tls: {}`, I got an error about activated TLS but missing commonName.

I suspect some kind of `if tls: config.tls = tls` logic. :)

**What you expected to happen**:

Plain http request for matching prefixes.

**How to reproduce it (as minimally and precisely as possible)**:

See example above: set up a server with TLS by default and try to disable it for a certain prefix.  Null does nothing, false explodes in the parser, and `{}` complains about missing commonName.

**Anything else we need to know?**:

`¯\_(ツ)_/¯`

**Environment**:

- linkerd/namerd version, config files: linkerd/namerd are 1.3.5

The rest of the platform shouldn't matter (Ubuntu Xenial on metal tho).
