### ISSUE TITLE
support which namespace is used in request http header

### ISSUE THREAD

**Issue by Xcorpio** [linkerd/linkerd#1869]
## Filing a Linkerd issue ##

Issue Type:

- [ ] Bug report
- [x] Feature request

**What happened**:
hi, i am writing a api test tool and use `linkerd` as a request dynamic routing server. i have many namespace which represent different environments like `prod`, `test`, `mock-servers01`, `mock-servers02` and may increase dynamically in namerd. 
i expect there has a user headers like `l5d-dtab` which can specify a namespace in linkerd.
**Environment**:
- linkerd/namerd version, config files:
 1.3.6
linkerd config:
```
admin:
  ip: 0.0.0.0
  port: 9990

routers:
- protocol: http
  interpreter:
    kind: io.l5d.namerd
    namespace: default
    dst: /$/inet/localhost/4100
  httpAccessLog: logs/access.log
  label: indigo
  servers:
  - ip: 0.0.0.0
    port: 4140
```
- Platform, version, and config files (Kubernetes, DC/OS, etc):
  > localhost
