### ISSUE TITLE
1.4.0 stopped serving chain certificates

### ISSUE THREAD

**Issue by hynek** [linkerd/linkerd#1926]
# Thanks for your help improving the project! #

## Filing a Linkerd issue ##

Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:

After upgrading from 1.3.7, HAProxy's health check started failing with

    `bk-l5d-router-slow/l5d-local is DOWN, reason: Layer6 invalid response, info: "SSL handshake failure"`

and Python connections with

    [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

Turns out, that with the same config and the same PEM files, linkerd stopped serving chain files that are part of `certPath`.

1.3.7:

```
depth=2 C = DE, ST = BB, L = Potsdam, O = Variomedia AG, CN = ca.vm.ag, emailAddress = ca@vm.ag
verify return:1
depth=1 CN = ca.vm.ag
verify return:1
depth=0 CN = *.host.vrmd.de
verify return:1
---
Certificate chain
 0 s:/CN=*.host.vrmd.de
   i:/CN=ca.vm.ag
 1 s:/CN=ca.vm.ag
   i:/C=DE/ST=BB/L=Potsdam/O=Variomedia AG/CN=ca.vm.ag/emailAddress=ca@vm.ag
```

1.4.0

```
depth=0 CN = *.host.vrmd.de
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = *.host.vrmd.de
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/CN=*.host.vrmd.de
   i:/CN=ca.vm.ag
```

It's *not* because of the order inside the file because if I flip them, the key fails to load.

I strongly presume this is related to the Finagle upgrade but I’m baffled that I’m the only person running into it.

**What you expected to happen**:

Nothing actually. I’d like it to keep working. 😇

**How to reproduce it (as minimally and precisely as possible)**:

`¯\_(ツ)_/¯`

**Anything else we need to know?**:

` ¯\_(ツ)_/¯`

**Comment by dadjeibaah** [comment]
Thanks for filing this issue @hynek! We will take a look at what's going on

**Comment by adleong** [comment]
@hynek Yikes, this is my top priority issue.  If you can provide any of the following information, it will greatly help tracking this down:

* What protocol? http or h2?
* Can you provide your Linkerd config?
* Can you provide your cert PEM file (without private key)?
  * If not, can you provide instructions for how to generate a cert with the same structure?

If you'd rather share any of the above privately instead of publicly, you can private message me on the Linkerd slack or email me alex@buoyant.io

**Comment by hynek** [comment]
I’m travelling and on my phone right now. I can send you the pem file and config later. I’m fairly confident it’s created using HashiCorp’s Vault CA capabilities.

**Comment by hynek** [comment]
Here’s our config template for now. Both admin and servers have the same problem.

``` yaml
---
admin:
  port: 9990
  ip: {{ linkerd.admin.address }}
  tls:
    certPath: /etc/ssl/certs/*.host.vrmd.de_all.crt
    keyPath: /etc/ssl/private/*.host.vrmd.de.pkcs8


namers:
  - kind: io.l5d.consul
    includeTag: false
    useHealthCheck: true
    token: XXX


routers:
  - protocol: http
    label: /http-consul

    interpreter:
      kind: io.l5d.mesh
      dst: /#/io.l5d.consul/.local/namerd
      experimental: true
      root: /default

    servers:
      - port: 4140
        ip: {{ linkerd.router.address }}
        addForwardedHeader:
          by:
            kind: ip
          for:
            kind: ip
        tls:
          certPath: /etc/ssl/certs/*.host.vrmd.de_all.crt
          keyPath: /etc/ssl/private/*.host.vrmd.de.pkcs8
        clearContext: {{ "true" if linkerd.edge else "false" }}

    client:
      kind: io.l5d.static
      configs:
        - prefix: /
          requeueBudget:
            percentCanRetry: 5.0
          tls:
            disableValidation: true

    service:
      kind: io.l5d.global
      responseClassifier:
        kind: io.l5d.http.retryableIdempotent5XX


telemetry:
  - kind: io.l5d.prometheus
    path: /admin/metrics/prometheus
    prefix: linkerd_


usage:
  enabled: false. # sorry :)
```

I double checked the logs if linkerd complains about cert loading but no dice.

I suspect the reason nobody ran into it yet is that we use an intermediate certificate to be able to revoke everything at once without compromising our root and that’s not that common? I suspect that’s a path for you to reproduce.
