### ISSUE TITLE
TLS prefix should include all transformers used in linkerd config

### ISSUE THREAD

**Issue by dadjeibaah** [linkerd/linkerd#1930]
**What happened**:
A user ran into TLS issues when using Client TLS with a prefix configuration. Below is a portion of the config that caused the problem.

```YAML
namers:
    - kind: io.l5d.k8s
      prefix: /io.l5d.k8s.out
      host: localhost
      port: 8001
      transformers:
      - kind: io.l5d.k8s.daemonset
        namespace: default
        port: incoming
        service: l5d
        hostNetwork: true
routers:
    - protocol: http
      label: outgoing
      dtab: |
        /k8s          =>   /#/io.l5d.k8s.out;
        /portNsSvc    =>   /#/portNsSvcToK8s;
        /host         =>   /portNsSvc/http/default;
        /host         =>   /portNsSvc/http;
        /svc          =>   /$/io.buoyant.http.domainToPathPfx/host;
servers:
      - port: 4140
        ip: 0.0.0.0
      client:
        kind: io.l5d.static
        configs:
        - prefix: /#/io.l5d.k8s.out
          tls:
            commonName: linkerd
            trustCerts:
            - /io.buoyant/linkerd/tls/ca.crt
``` 

The issue is that when linkerd is building client names for routing, transformers present in the linkerd configuration will be prepended to a client's dtab name. At the end of the identification phase, in the example above, Linkerd will have a name in the form of:
```
/io.l5d.k8s.daemonset/default/incoming/l5d/#/io.l5d.k8s.out/<k8s service name>...
```
This name does not match the client prefix name specified in the client TLS section. Because of this, linkerd unable to initiate TLS for outgoing clients.

This behavior is not really documented anywhere and it is pretty subtle. So, we should update the docs to highlight this.
