### ISSUE TITLE
http://world works BUT http://hello fails while following BUOYANT blog

### ISSUE THREAD

**Issue by Hugh-ifly** [linkerd/linkerd#1938]
## Filing a Linkerd issue ##

**Issue Type**:

- [yes] Bug report
- [ ] Feature request

**What happened**:
https://buoyant.io/2016/10/04/a-service-mesh-for-kubernetes-part-i-top-line-service-metrics/
I followed the blog above, but got stuck. I'm wondering how to debug and solve it.

**What you expected to happen**:
curl http://hello and get the expected result.

**How to reproduce it (as minimally and precisely as possible)**:
Here is my environment and operations:
1. Environment:
(1) kubernetes cluster, deployed at 10.1.86.22(master and node), 192.168.86.171(node). kubernetes version: 1.6.13
(2) linkerd, version 1.3
2. operations:
(1)`kubectl apply -f https://raw.githubusercontent.com/linkerd/linkerd-examples/master/k8s-daemonset/k8s/linkerd.yml`
 and I modified this YAML file in line 66,67 to set the correct namers:
```
            namers:
            - kind: io.l5d.k8s
              host: 10.1.86.22   # previous value was: localhost
              port: 8080           # previous vlaue was: 8001
```
 and routers:
```
           routers:
           - protocol: http
              ......
              interpreter:
                kind: default
                transformers:
                - kind: io.l5d.k8s.daemonset
                   namespace: default
                   port: incoming
                   service: l5d
                   k8sHost: 10.1.86.22   # I added this k8s master host and port
                   k8sPort: 8080            # I added this k8s master host and port
```

(2) `kubectl apply -f https://raw.githubusercontent.com/linkerd/linkerd-examples/master/k8s-daemonset/k8s/node-name-test.yml`
      `kubectl logs node-name-test`
      then I got this error log: 
``` 
          ;; connection timed out; no servers could be reached
```

(3) Following the blog, I chose the legacy version of hello world:
       `kubectl apply -f https://raw.githubusercontent.com/linkerd/linkerd-examples/master/k8s-daemonset/k8s/hello-world-legacy.yml` 

(4) Since external load balancer support was unavailable, I use hostIP directly:
     `http_proxy=192.168.86.171:32562 curl -s -v  http://hello`
    however, it failed:
```
* Rebuilt URL to: http://hello/
* Hostname was NOT found in DNS cache
*   Trying 192.168.86.171...
* Connected to 192.168.86.171 (192.168.86.171) port 32562 (#0)
> GET http://hello/ HTTP/1.1
> User-Agent: curl/7.35.0
> Host: hello
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 503 Service Unavailable
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Tue, 08 May 2018 12:33:04 GMT
< Content-Length: 83
< l5d-success-class: 0.0
< Via: 1.1 linkerd, 1.1 linkerd
< 
Get http://world: proxyconnect tcp: dial tcp :4140: getsockopt: connection refused
* Connection #0 to host 192.168.86.171 left intact
```

(5) But if I try http://world, it works:
  `http_proxy=192.168.86.171:32562 curl -s -v  http://world`

```
* Rebuilt URL to: http://world/
* Hostname was NOT found in DNS cache
*   Trying 192.168.86.171...
* Connected to 192.168.86.171 (192.168.86.171) port 32562 (#0)
> GET http://world/ HTTP/1.1
> User-Agent: curl/7.35.0
> Host: world
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 OK
< Date: Tue, 08 May 2018 12:35:53 GMT
< Content-Length: 21
< Content-Type: text/plain; charset=utf-8
< l5d-success-class: 1.0
< Via: 1.1 linkerd, 1.1 linkerd
< 
* Connection #0 to host 192.168.86.171 left intact
```

(6) Here is some logs in linkerd container:
```
I 0508 11:38:30.067 UTC THREAD10: Reaping /svc/world
I 0508 11:38:30.182 UTC THREAD10: Reaping %/io.l5d.k8s.daemonset/default/incoming/l5d/#/io.l5d.k8s/default/http/world-v1
I 0508 11:48:30.206 UTC THREAD10: Reaping /svc/hello
I 0508 11:48:30.255 UTC THREAD10: Reaping %/io.l5d.k8s.localnode/172.16.26.11/#/io.l5d.k8s/default/http/hello
I 0508 11:52:24.352 UTC THREAD95 TraceId:80af91c6f75d067e: FailureAccrualFactory marking connection to "%/io.l5d.k8s.daemonset/default/incoming/l5d/#/io.l5d.k8s/default/http/hello" as dead. Remote Address: Inet(/172.16.26.11:4141,Map(nodeName -> 10.1.86.22))
I 0508 11:52:24.367 UTC THREAD93 TraceId:80af91c6f75d067e: FailureAccrualFactory marking connection to "%/io.l5d.k8s.daemonset/default/incoming/l5d/#/io.l5d.k8s/default/http/hello" as dead. Remote Address: Inet(/172.16.66.2:4141,Map(nodeName -> 192.168.86.171))
I 0508 11:52:24.743 UTC THREAD46 TraceId:80af91c6f75d067e: FailureAccrualFactory marking connection to "%/io.l5d.k8s.localnode/172.16.26.11/#/io.l5d.k8s/default/http/hello" as dead. Remote Address: Inet(/172.16.26.12:7777,Map(nodeName -> 10.1.86.22))
I 0508 11:52:24.755 UTC THREAD47 TraceId:80af91c6f75d067e: FailureAccrualFactory marking connection to "%/io.l5d.k8s.localnode/172.16.26.11/#/io.l5d.k8s/default/http/hello" as dead. Remote Address: Inet(/172.16.26.14:7777,Map(nodeName -> 10.1.86.22))
I 0508 11:58:41.984 UTC THREAD93 TraceId:2f1a90e9c02572c2: FailureAccrualFactory marking connection to "%/io.l5d.k8s.daemonset/default/incoming/l5d/#/io.l5d.k8s/default/http/hello" as dead. Remote Address: Inet(/172.16.66.2:4141,Map(nodeName -> 192.168.86.171))
I 0508 11:58:42.007 UTC THREAD54 TraceId:2f1a90e9c02572c2: FailureAccrualFactory marking connection to "%/io.l5d.k8s.localnode/172.16.26.11/#/io.l5d.k8s/default/http/hello" as dead. Remote Address: Inet(/172.16.26.14:7777,Map(nodeName -> 10.1.86.22))
I 0508 11:58:42.011 UTC THREAD95 TraceId:2f1a90e9c02572c2: FailureAccrualFactory marking connection to "%/io.l5d.k8s.daemonset/default/incoming/l5d/#/io.l5d.k8s/default/http/hello" as dead. Remote Address: Inet(/172.16.26.11:4141,Map(nodeName -> 10.1.86.22))
I 0508 11:58:42.023 UTC THREAD55 TraceId:2f1a90e9c02572c2: FailureAccrualFactory marking connection to "%/io.l5d.k8s.localnode/172.16.26.11/#/io.l5d.k8s/default/http/hello" as dead. Remote Address: Inet(/172.16.26.12:7777,Map(nodeName -> 10.1.86.22))
```
**Anything else we need to know?**:

**Environment**:
- linkerd 1.3
- Kubernetes 1.6.13, cluster mode
