### ISSUE TITLE
gRPC server not receiving l5d-ctx-dtab header from Linkerd

### ISSUE THREAD

**Issue by bmcmilla** [linkerd/linkerd#1945]
Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:

Linkerd seems to be dropping the `l5d-dtab` header on gRPC requests.

For example, external request to Service A, and Service A calls Service B.  The external request contains a `l5d-dtab` header selecting specific versions of Service A and Service B.

We see the request routed to Service A per `l5d-dtab` but the call to Service B routes to the default version of Service B.

Found in the Service A logs that the server did not receive a `l5d-ctx-dtab` header from Linkerd and consequently could not pass along the header in the call to Service B.

**What you expected to happen**:

Expected the destination server to receive the original client's dtab in a `l5d-ctx-dtab` header.

**How to reproduce it (as minimally and precisely as possible)**:

1. Namerd dtab:

```
/srv=>/#/io.l5d.k8s/m6a/grpc;
/svc=>/$/io.buoyant.http.domainToPathPfx/grpc;
/grpc/Search=>/srv/search-v1-0-6|/srv/search-v1-0-6;
/grpc/ChannelList=>/srv/channellist-v1-0-3|/srv/channellist-v1-0-3;
```

2. `ld5-dtab` header set by grpc-java client set on a search request:

```
metadata.put(Metadata.Key.of("l5d-dtab", Metadata.ASCII_STRING_MARSHALLER), "/grpc/Search => /srv/search-edge; /grpc/ChannelList => /srv/channellist-edge");
```

3.  Server logs indicate request routed to search-edge and channellist-v1-0.3 pods.  Expected search-edge and channellist-edge.

4.  Request headers logged by search-edge:

```
headers=Metadata(grpc-accept-encoding=gzip, devicetimezone=America/New_York, l5d-dst-service=/svc/search.Search, l5d-reqid=ed03c39fd4c1891a, l5d-dst-client=/#/io.l5d.k8s/m6a/grpc/search-edge, via=h2 linkerd, grpc-trace-bin=, l5d-ctx-trace=XI9zgVoKC6LtA8Of1MGJGu0Dw5/UwYkaAAAAAAAAAAA=, content-type=application/grpc, user-agent=grpc-java-netty/1.8.0, l5d-dst-residual=/search)
```

**Environment**:

- linkerd/namerd version, config files: See config below:  linkerd 1.3.7, namerd 1.3.7
- Platform, version, and config files (Kubernetes, DC/OS, etc):  Kubernetes 1.7
- Cloud provider or hardware configuration:  N/A

Relevant configs:

```
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: l5d
  name: l5d
spec:
  template:
    metadata:
      labels:
        app: l5d
    spec:
      volumes:
      - name: l5d-config
        configMap:
          name: "l5d-config"
      containers:
      - name: l5d
        resources:
          limits:
            cpu: 500m
            memory: 1G
        image: buoyantio/linkerd:1.3.7
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - /io.buoyant/linkerd/config/config.yaml
        ports:
        - name: incoming
          containerPort: 4140
        - name: admin
          containerPort: 9990
        volumeMounts:
        - name: "l5d-config"
          mountPath: "/io.buoyant/linkerd/config"
          readOnly: true
      - name: kubectl
        image: buoyantio/kubectl:v1.4.0
        args:
        - "proxy"
        - "-p"
        - "8001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: l5d-config
data:
  config.yaml: |-
    admin:
      ip: 0.0.0.0
      port: 9990
    usage:
      orgId: linkerd-m6a
      enabled: false
    routers:
    - label: grpc-incoming
      protocol: h2
      experimental: true
      identifier:
        kind: io.l5d.header.path
        segments: 1
      interpreter:
        kind: io.l5d.namerd
        dst: /$/inet/namerd.m6a-service-mesh.svc.cluster.local/4100
        namespace: internal
      servers:
      - port: 4140
        ip: 0.0.0.0
      service:
        responseClassifier:
          kind: io.l5d.h2.grpc.default
```
