### ISSUE TITLE
Linkerd >= 1.4.0 no longer validates intermediate certs presented by servers during mTLS

### ISSUE THREAD

**Issue by joeyb** [linkerd/linkerd#1957]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:

With linkerd >= 1.4.0, requests to servers that have intermediates in their cert file now fail. It looks like the client-side no longer follows the presented cert chain when it attempts to validate the server's certs against the client's configured `trustCerts`. This causes the client to not send along its certs, leading to an internal `SSLV3_ALERT_HANDSHAKE_FAILURE` exception.

**What you expected to happen**:

The client-side linkerd should walk the cert chain and test each issuer against those in `trustCerts`, not just the leaf cert.

**How to reproduce it (as minimally and precisely as possible)**:

https://github.com/joeyb/linkerd-cert-issue

**Environment**:
linkerd >= 1.4.0

**Comment by wmorgan** [comment]
Is this a dup of #1926?

**Comment by joeyb** [comment]
@wmorgan - Nope, the repro is using the `nightly` image, which already includes the changes from #1926.

I suspect this does at least tie back to the same finagle API changes that lead to #1926, but they are separate issues.

**Comment by adleong** [comment]
@joeyb thanks for filing this and for the detailed repro steps!  Do you know if client auth is required to trigger this?  Does the client still fail to validate the server cert chain if it does not use client auth?

**Comment by joeyb** [comment]
@adleong - It looks like client auth *is* required to trigger the issue. I modified my repro to use the following `linkerd.yaml` and now `curl localhost:4140` returns successfully.

```yaml
admin:
  ip: 0.0.0.0
  port: 9990

routers:
- protocol: http
  label: server
  dtab: |
    /svc => /$/inet/hello/80
  servers:
  - ip: 0.0.0.0
    port: 4141
    tls:
      caCertPath: /io.buoyant/certs/ca/certs/ca.cert.pem
      certPath: /io.buoyant/certs/ca/intermediate/certs/hello-with-intermediate.cert.pem
      keyPath: /io.buoyant/certs/ca/intermediate/private/hello.key.pkcs8.pem
      serverCaChainPath: /io.buoyant/certs/ca/intermediate/certs/hello-with-intermediate.cert.pem

- protocol: http
  label: client
  dtab: |
    /svc => /$/inet/localhost/4141
  servers:
  - ip: 0.0.0.0
    port: 4140
  client:
    tls:
      commonName: "hello"
      trustCerts:
      - /io.buoyant/certs/ca/certs/ca.cert.pem
```
