### ISSUE TITLE
namerd: HTTP 500 on dtab DELETE

### ISSUE THREAD

**Issue by utrack** [linkerd/linkerd#1967]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
I receive HTTP 500 when trying to DELETE the router/rule set.

**What you expected to happen**:
HTTP 200, set deleted

**How to reproduce it (as minimally and precisely as possible)**:
dtab router exists:
```
curl -v "http://localhost:8001/api/v1/namespaces/linkerd/services/namerd:4180/proxy/api/1/dtabs/qwe"     
[null,null,null,null,{"prefix":"/your/base/3","dst":"/us/3"},null,null,null,null,null]
* Connection #0 to host localhost left intact
```

but I get 500 on deletion:
```
curl -v -XDELETE "http://localhost:8001/api/v1/namespaces/linkerd/services/namerd:4180/proxy/api/1/dtabs/qwe"                *   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8001 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8001 (#0)
> DELETE /api/v1/namespaces/linkerd/services/namerd:4180/proxy/api/1/dtabs/qwe HTTP/1.1
> Host: localhost:8001
> User-Agent: curl/7.60.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< Date: Wed, 30 May 2018 14:00:02 GMT
<
* Connection #0 to host localhost left intact
```

**Anything else we need to know?**:
Not sure, but I can provide any info on request

**Environment**:
```
bare metal, k8s v1.9.5.
buoyantio/namerd:1.3.6
buoyantio/linkerd:1.3.6
```
```
kc describe configmap -n linkerd l5d-config                                                              2018-05-30 17:02:22
Name:         l5d-config
Namespace:    linkerd
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","data":{"config.yaml":"admin:\n  ip: 0.0.0.0\n  port: 9990\n\n# Namers provide Linkerd with service discovery information.  To use a...

Data
====
config.yaml:
----
admin:
  ip: 0.0.0.0
  port: 9990

# Namers provide Linkerd with service discovery information.  To use a
# namer, you reference it in the dtab by its prefix.  We define 4 namers:
# * /io.l5d.k8s gets the address of the target app
# * /io.l5d.k8s.http gets the address of the http-incoming Linkerd router on the target app's node
# * /io.l5d.k8s.h2 gets the address of the h2-incoming Linkerd router on the target app's node
# * /io.l5d.k8s.grpc gets the address of the grpc-incoming Linkerd router on the target app's node
namers:
- kind: io.l5d.k8s
- kind: io.l5d.k8s
  prefix: /io.l5d.k8s.http
  transformers:
    # The daemonset transformer replaces the address of the target app with
    # the address of the http-incoming router of the Linkerd daemonset pod
    # on the target app's node.
  - kind: io.l5d.k8s.daemonset
    namespace: linkerd
    port: http-incoming
    service: l5d
    hostNetwork: true # Uncomment if using host networking (eg for CNI)
- kind: io.l5d.k8s
  prefix: /io.l5d.k8s.h2
  transformers:
    # The daemonset transformer replaces the address of the target app with
    # the address of the h2-incoming router of the Linkerd daemonset pod
    # on the target app's node.
  - kind: io.l5d.k8s.daemonset
    namespace: linkerd
    port: h2-incoming
    service: l5d
    hostNetwork: true # Uncomment if using host networking (eg for CNI)
- kind: io.l5d.k8s
  prefix: /io.l5d.k8s.grpc
  transformers:
    # The daemonset transformer replaces the address of the target app with
    # the address of the grpc-incoming router of the Linkerd daemonset pod
    # on the target app's node.
  - kind: io.l5d.k8s.daemonset
    namespace: linkerd
    port: grpc-incoming
    service: l5d
    hostNetwork: true # Uncomment if using host networking (eg for CNI)
- kind: io.l5d.rewrite
  prefix: /portNsSvcToK8s
  pattern: "/{port}/{ns}/{svc}"
  name: "/k8s/{ns}/{port}/{svc}"

# Telemeters export metrics and tracing data about Linkerd, the services it
# connects to, and the requests it processes.
telemetry:
- kind: io.l5d.prometheus # Expose Prometheus style metrics on :9990/admin/metrics/prometheus
- kind: io.l5d.recentRequests
  sampleRate: 0.25 # Tune this sample rate before going to production
# - kind: io.l5d.zipkin # Uncomment to enable exporting of zipkin traces
#   host: zipkin-collector.default.svc.cluster.local # Zipkin collector address
#   port: 9410
#   sampleRate: 1.0 # Set to a lower sample rate depending on your traffic volume

# Usage is used for anonymized usage reporting.  You can set the orgId to
# identify your organization or set `enabled: false` to disable entirely.
usage:
  orgId: linkerd-examples-servicemesh

# Routers define how Linkerd actually handles traffic.  Each router listens
# for requests, applies routing rules to those requests, and proxies them
# to the appropriate destinations.  Each router is protocol specific.
# For each protocol (HTTP, HTTP/2, gRPC) we define an outgoing router and
# an incoming router.  The application is expected to send traffic to the
# outgoing router which proxies it to the incoming router of the Linkerd
# running on the target service's node.  The incoming router then proxies
# the request to the target application itself.  We also define HTTP and
# HTTP/2 ingress routers which act as Ingress Controllers and route based
# on the Ingress resource.
routers:
- label: http-outgoing
  protocol: http
  interpreter:
    kind: io.l5d.namerd
    dst: /#/io.l5d.k8s/linkerd/thrift/namerd
    namespace: outgoing
    #transformers:
    #- kind: io.l5d.k8s.daemonset
    #  namespace: linkerd
    #  port: http-incoming
    #  service: l5d
  servers:
  - port: 4140
    ip: 0.0.0.0
  service:
    responseClassifier:
      kind: io.l5d.http.retryableRead5XX
  client:
    kind: io.l5d.static
    configs:
    # Use HTTPS if sending to port 443
    - prefix: "/$/io.buoyant.rinet/443/{service}"
      tls:
        commonName: "{service}"

- label: http-incoming
  protocol: http
  interpreter:
    kind: io.l5d.namerd
    dst: /#/io.l5d.k8s/linkerd/thrift/namerd
    namespace: incoming
  servers:
  - port: 4141
    ip: 0.0.0.0

- label: h2-outgoing
  protocol: h2
  servers:
  - port: 4240
    ip: 0.0.0.0
  dtab: |
    /ph  => /$/io.buoyant.rinet ;                       # /ph/80/google.com -> /$/io.buoyant.rinet/80/google.com
    /svc => /ph/80 ;                                    # /svc/google.com -> /ph/80/google.com
    /svc => /$/io.buoyant.porthostPfx/ph ;              # /svc/google.com:80 -> /ph/80/google.com
    /k8s => /#/io.l5d.k8s.h2 ;                          # /k8s/default/h2/foo -> /#/io.l5d.k8s.h2/default/h2/foo
    /portNsSvc => /#/portNsSvcToK8s ;                   # /portNsSvc/h2/default/foo -> /k8s/default/h2/foo
    /host => /portNsSvc/h2/default ;                    # /host/foo -> /portNsSvc/h2/default/foo
    /host => /portNsSvc/h2 ;                            # /host/default/foo -> /portNsSvc/h2/default/foo
    /svc => /$/io.buoyant.http.domainToPathPfx/host ;   # /svc/foo.default -> /host/default/foo
  client:
    kind: io.l5d.static
    configs:
    # Use HTTPS if sending to port 443
    - prefix: "/$/io.buoyant.rinet/443/{service}"
      tls:
        commonName: "{service}"

- label: h2-incoming
  protocol: h2
  servers:
  - port: 4241
    ip: 0.0.0.0
  interpreter:
    kind: default
    #transformers:
    #- kind: default
    #  hostNetwork: true # Uncomment if using host networking (eg for CNI)
  dtab: |
    /k8s => /#/io.l5d.k8s ;                             # /k8s/default/h2/foo -> /#/io.l5d.k8s/default/h2/foo
    /portNsSvc => /#/portNsSvcToK8s ;                   # /portNsSvc/h2/default/foo -> /k8s/default/h2/foo
    /host => /portNsSvc/h2/default ;                    # /host/foo -> /portNsSvc/h2/default/foo
    /host => /portNsSvc/h2 ;                            # /host/default/foo -> /portNsSvc/h2/default/foo
    /svc => /$/io.buoyant.http.domainToPathPfx/host ;   # /svc/foo.default -> /host/default/foo

- label: grpc-outgoing
  protocol: h2
  servers:
  - port: 4340
    ip: 0.0.0.0
  identifier:
    kind: io.l5d.header.path
    segments: 1
  dtab: |
    /hp  => /$/inet ;                                # /hp/linkerd.io/8888 -> /$/inet/linkerd.io/8888
    /svc => /$/io.buoyant.hostportPfx/hp ;           # /svc/linkerd.io:8888 -> /hp/linkerd.io/8888
    /srv => /#/io.l5d.k8s.grpc/default/grpc;         # /srv/service/package -> /#/io.l5d.k8s.grpc/default/grpc/service/package
    /svc => /$/io.buoyant.http.domainToPathPfx/srv ; # /svc/package.service -> /srv/service/package
  client:
    kind: io.l5d.static
    configs:
    # Always use TLS when sending to external grpc servers
    - prefix: "/$/inet/{service}"
      tls:
        commonName: "{service}"

- label: gprc-incoming
  protocol: h2
  servers:
  - port: 4341
    ip: 0.0.0.0
  identifier:
    kind: io.l5d.header.path
    segments: 1
  interpreter:
    kind: default
    #transformers:
    #- kind: default
    #  hostNetwork: true # Uncomment if using host networking (eg for CNI)
  dtab: |
    /srv => /#/io.l5d.k8s/default/grpc ;             # /srv/service/package -> /#/io.l5d.k8s/default/grpc/service/package
    /svc => /$/io.buoyant.http.domainToPathPfx/srv ; # /svc/package.service -> /srv/service/package

# HTTP Ingress Controller listening on port 80
- protocol: http
  label: http-ingress
  servers:
    - port: 80
      ip: 0.0.0.0
      clearContext: true
  identifier:
    kind: io.l5d.ingress
  dtab: /svc => /#/io.l5d.k8s

# HTTP/2 Ingress Controller listening on port 8080
- protocol: h2
  label: h2-ingress
  servers:
    - port: 8080
      ip: 0.0.0.0
      clearContext: true
  identifier:
    kind: io.l5d.ingress
  dtab: /svc => /#/io.l5d.k8s
Events:  <none>
```

```
kc describe configmap -n linkerd namerd-config                                                           2018-05-30 17:02:30
Name:         namerd-config
Namespace:    linkerd
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","data":{"config.yml":"admin:\n  ip: 0.0.0.0\n  port: 9991\n\nnamers:\n- kind: io.l5d.k8s\n  host: localhost\n  port: 8001\n\nstorage...

Data
====
config.yml:
----
admin:
  ip: 0.0.0.0
  port: 9991

namers:
- kind: io.l5d.k8s
  host: localhost
  port: 8001

storage:
  kind: io.l5d.k8s
  host: localhost
  port: 8001
  namespace: default

interfaces:
- kind: io.l5d.thriftNameInterpreter
  ip: 0.0.0.0
  port: 4100
- kind: io.l5d.httpController
  ip: 0.0.0.0
  port: 4180
- kind: io.l5d.mesh
  ip: 0.0.0.0
  port: 4321
Events:  <none>
```
