### ISSUE TITLE
General OpenSslEngine problem at remote address

### ISSUE THREAD

**Issue by mrezaei00** [linkerd/linkerd#1985]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
Upgrading to Linkerd `1.4.0` with the same client/server configuration causes the following error:
```
General OpenSslEngine problem at remote address: /10.16.0.94:4141. Remote Info: Not Available
```

**What you expected to happen**:
I expected Linkerd `1.4.0` to continue working with the same configuration.
HTTP server config example:
```
      servers:
      - port: 4140
        ip: 0.0.0.0
      client:
        tls:
          commonName: "star.domain.inc.com"
```
HTTP client config example:
```
      servers:
      - port: 4141
        ip: 0.0.0.0
        tls:
          certPath: /certs/wildcard-proxycert
          keyPath: /certs/wildcard-proxykey
```

**How to reproduce it (as minimally and precisely as possible)**:
1. Run Linkerd `1.3.6`
1. Configure it with the client and server TLS as mentioned above.
1. Update Linkerd to `1.4.0` (this was tested using the [`linkerd-zipkin`](https://github.com/linkerd/linkerd-zipkin) build running in Kubernetes).
1. Send a request to the outgoing proxy and the error above is returned.

**Anything else we need to know?**:
This issue happened to both HTTP and HTTP/2 requests after the update to `1.4.0`.

**Environment**:
- linkerd/namerd version, config files: Linkerd `1.4.0`, Namerd `1.3.6`, HTTP config example as follows:
```
    - protocol: http
      label: out-http
      identifier:
        kind: io.l5d.path
        segments: 2
        consume: false
      interpreter:
        kind: io.l5d.mesh
        root: /out-http
        dst: /$/inet/<namerd_dns>/4321
      servers:
      - port: 4140
        ip: 0.0.0.0
      client:
        tls:
          commonName: "star.domain.inc.com"

    - protocol: http
      label: in-http
      identifier:
        kind: io.l5d.path
        segments: 2
        consume: true
      interpreter:
        kind: io.l5d.mesh
        root: /in-http
        dst: /$/inet/<namerd_dns>/4321
      servers:
      - port: 4141
        ip: 0.0.0.0
        tls:
          certPath: /certs/wildcard-proxycert
          keyPath: /certs/wildcard-proxykey
```
- Platform, version, and config files (Kubernetes, DC/OS, etc): Kubernetes `1.10.2`
- Cloud provider or hardware configuration: Google Cloud Platform

**Comment by adleong** [comment]
Hi @mrezaei00, what is the structure of the `wildcard-proxycert` file?  If it contains more than one cert (ie a cert chain) then you'll need to use the `intermediateCertsPath` option which was added in Linkerd 1.4.1 (https://github.com/linkerd/linkerd/releases/tag/1.4.1).

**Comment by mrezaei00** [comment]
@adleong the `wildcard-proxycert` is a single file/certification with a wildcard Common Name, e.g. `*.domain.inc.com`. Does the `intermediateCertsPath` still apply to my situation?

**Comment by adleong** [comment]
Thanks for the info @mrezaei00.  In that case, no, `intermediateCertsPath` should not apply.  Let me see if I can reproduce this issue.

**Comment by adleong** [comment]
I wasn't able to reproduce this.  I used a slightly simplified setup, taking Namerd out of the equation and using self-signed certs.  With this setup, requests were routed correctly and Linkerd-Linkerd requests were encrypted as I'd expect.  Here's the Linkerd config I used:

```
namers: []

routers:
- protocol: http
  label: out-http
  identifier:
    kind: io.l5d.path
    segments: 2
    consume: false
  dtab: /svc/* => /$/inet/localhost/4141
  servers:
  - port: 4140
  client:
    tls:
      commonName: "foobar.domain.inc.com"
      trustCerts:
      - certificates/cacertificate.pem

- protocol: http
  label: in-http
  identifier:
    kind: io.l5d.path
    segments: 2
    consume: true
  servers:
  - port: 4141
    tls:
      certPath: certificates/servercert.pem
      keyPath: certificates/private/serverkey.pk8
  dtab: /svc/* => /$/inet/localhost/8888
```

and here is the server cert:

```
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 4100 (0x1004)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, CN=My CA
        Validity
            Not Before: Jun 15 23:55:17 2018 GMT
            Not After : May 22 23:55:17 2118 GMT
        Subject: CN=*.domain.inc.com, C=US
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:d2:ba:9a:00:5f:c7:5f:f1:25:94:e3:28:16:81:
                    20:fd:3d:a6:f2:0a:62:38:c0:6c:dc:45:ce:22:1e:
                    3a:7d:3e:f0:d8:a8:68:b6:90:40:8b:c5:11:26:f3:
                    6a:41:0a:5d:be:ff:63:fc:7e:f4:b6:4a:b3:72:76:
                    06:5a:8c:8c:01:1a:29:61:f1:48:1a:7c:a3:ca:01:
                    43:e2:f6:5b:66:aa:4a:4b:f7:26:56:0a:6f:a6:ac:
                    f8:50:47:13:49:c4:4c:3f:ee:c2:92:e1:bf:32:b9:
                    d8:2b:70:11:f1:1e:ad:90:ba:1a:49:4d:c5:36:ca:
                    13:8e:94:25:20:90:a4:17:58:31:84:7a:9d:dd:95:
                    39:b9:5f:b1:bf:30:92:05:09:7d:da:a9:36:93:95:
                    4b:43:70:19:a5:1a:96:2f:4d:ee:cd:57:af:b7:b5:
                    89:f6:80:67:e6:4c:6d:7f:90:7a:4b:3a:e0:87:31:
                    16:0e:46:55:5a:d5:28:a6:b4:e1:5b:b0:3a:5d:d8:
                    50:6c:e4:bb:3c:77:76:9d:d6:41:74:10:b6:0d:7d:
                    50:aa:10:e5:0c:75:4d:d7:0d:6f:4c:9d:9c:51:c7:
                    28:26:e0:10:a8:4b:18:b2:2a:5f:ac:9a:5a:68:2a:
                    4e:fb:a2:03:10:00:2a:86:3b:39:3e:65:5b:0a:33:
                    72:c7
                Exponent: 65537 (0x10001)
    Signature Algorithm: sha256WithRSAEncryption
         4d:f3:32:dd:b5:33:42:5f:8a:e7:16:60:19:74:44:e0:cf:34:
         f4:ce:74:b7:cf:30:f0:31:55:97:e3:f2:52:ad:b0:7a:c2:96:
         e3:31:73:96:3f:07:9e:b4:10:89:38:3d:cd:16:e2:d4:98:3b:
         c3:b3:4d:e5:74:02:5a:ba:55:28:37:9b:da:33:74:b1:84:90:
         ff:be:8c:fc:2a:d9:e0:f1:37:56:b8:11:be:09:cf:18:b7:a7:
         a4:49:7b:4a:0d:a0:f6:af:45:6e:0f:f6:ab:ec:ef:b5:ab:b8:
         65:b5:08:79:ae:fb:3b:f2:da:e8:76:07:a6:b1:8b:98:f3:f6:
         c4:d8:72:65:43:5b:b3:78:8c:83:84:74:69:bd:79:40:95:f8:
         40:f8:c1:02:86:26:c3:5d:d5:51:6e:8c:16:cf:32:3b:61:b3:
         ab:64:a3:9a:18:eb:33:27:c8:e1:67:eb:21:05:3c:9d:00:55:
         f6:72:82:1c:89:75:76:58:27:9e:8f:78:18:88:fb:3c:7b:7a:
         f9:be:d9:f6:e8:16:80:a9:f7:98:52:90:17:0f:8c:e1:93:10:
         c4:80:c9:cc:2e:bd:af:1a:20:06:57:07:85:b1:3c:8f:6b:3d:
         32:cd:89:3c:aa:8a:21:aa:ef:21:c2:76:4c:30:6f:19:49:d8:
         84:1b:fc:53
-----BEGIN CERTIFICATE-----
MIICvDCCAaQCAhAEMA0GCSqGSIb3DQEBCwUAMB0xCzAJBgNVBAYTAlVTMQ4wDAYD
VQQDDAVNeSBDQTAgFw0xODA2MTUyMzU1MTdaGA8yMTE4MDUyMjIzNTUxN1owKDEZ
MBcGA1UEAwwQKi5kb21haW4uaW5jLmNvbTELMAkGA1UEBhMCVVMwggEiMA0GCSqG
SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDSupoAX8df8SWU4ygWgSD9PabyCmI4wGzc
Rc4iHjp9PvDYqGi2kECLxREm82pBCl2+/2P8fvS2SrNydgZajIwBGilh8UgafKPK
AUPi9ltmqkpL9yZWCm+mrPhQRxNJxEw/7sKS4b8yudgrcBHxHq2QuhpJTcU2yhOO
lCUgkKQXWDGEep3dlTm5X7G/MJIFCX3aqTaTlUtDcBmlGpYvTe7NV6+3tYn2gGfm
TG1/kHpLOuCHMRYORlVa1SimtOFbsDpd2FBs5Ls8d3ad1kF0ELYNfVCqEOUMdU3X
DW9MnZxRxygm4BCoSxiyKl+smlpoKk77ogMQACqGOzk+ZVsKM3LHAgMBAAEwDQYJ
KoZIhvcNAQELBQADggEBAE3zMt21M0JfiucWYBl0RODPNPTOdLfPMPAxVZfj8lKt
sHrCluMxc5Y/B560EIk4Pc0W4tSYO8OzTeV0Alq6VSg3m9ozdLGEkP++jPwq2eDx
N1a4Eb4Jzxi3p6RJe0oNoPavRW4P9qvs77WruGW1CHmu+zvy2uh2B6axi5jz9sTY
cmVDW7N4jIOEdGm9eUCV+ED4wQKGJsNd1VFujBbPMjths6tko5oY6zMnyOFn6yEF
PJ0AVfZyghyJdXZYJ56PeBiI+zx7evm+2fboFoCp95hSkBcPjOGTEMSAycwuva8a
IAZXB4WxPI9rPTLNiTyqiiGq7yHCdkwwbxlJ2IQb/FM=
-----END CERTIFICATE-----
```

Do your certificates differ from the one I used significantly in structure?  Can you use `openssl s_client -connect localhost:4141` to get more information about the certificates that Linkerd is serving?

**Comment by mrezaei00** [comment]
@adleong structure looks quite different (and not a self-signed cert):
```
# openssl s_client -connect localhost:4141
CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 High Assurance Server CA
verify return:1
depth=0 C = US, ST = California, L = Palo Alto, O = "WePay, Inc.", CN = *.domain.inc.com
verify return:1
---
Certificate chain
 0 s:/C=US/ST=California/L=Palo Alto/O=WePay, Inc./CN=*.domain.inc.com
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
 1 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFZDCCBEygAwIBAgIQA00dEv5Kh2CNuX+vdbgWWjANBgkqhkiG9w0BAQsFADBw
...
yawYd01LF15VVQlIGGM2TMpWfUOZBpTh62Ux2iKq/SjVbUILdJKvWw==
-----END CERTIFICATE-----
subject=/C=US/ST=California/L=Palo Alto/O=WePay, Inc./CN=*.domain.inc.com
issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
---
No client certificate CA names sent
Peer signing digest: SHA256
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 3101 bytes and written 302 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: F4160F3B...D46C2
    Session-ID-ctx: 
    Master-Key: 2DDE231...F45B6
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1529292904
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---
```

**Comment by adleong** [comment]
@mrezaei00 I'm looking at the HTTP client config snippet you pasted in the description:
```
      servers:
      - port: 4141
        ip: 0.0.0.0
        tls:
          certPath: /certs/wildcard-proxycert
          keyPath: /certs/wildcard-proxykey
```

this looks like it's actually configuring TLS on the server (it's in the server section).  I think you need to have client TLS configured here instead:

```
      client:
        tls:
          certPath: /certs/wildcard-proxycert
          keyPath: /certs/wildcard-proxykey

```

**Comment by adleong** [comment]
I think I have managed to reproduce this using non-self signed certs.  I will investigate further.

**Comment by adleong** [comment]
I believe this may be related to https://github.com/twitter/finagle/issues/699

**Comment by mrezaei00** [comment]
Is the TLS config you mentioned still related or the issue is entirely due to the Finagle issue?

**Comment by adleong** [comment]
@mrezaei00 I think you just have a small typo in your description where you mixed up the server config and the client config which briefly confused me.  I will hopefully know more about the Finagle issue and how it related to Linkerd after I speak with someone from the Finagle team.

**Comment by adleong** [comment]
@mrezaei00 are there any errors in the outgoing Linkerd's logs when this error occurs?  

An error log including:

```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

perhaps?

**Comment by adleong** [comment]
Another thing to double check is that the DigiCert High Assurance EV Root CA is in your JVM's trust store:

```
$ keytool -list -rfc -storepass changeit -keystore $JAVA_HOME/jre/lib/security/cacerts  | grep -i DigiCert
Alias name: digicertassuredidrootca
Alias name: digicerthighassuranceevrootca
Alias name: digicertglobalrootca
```

**Comment by mrezaei00** [comment]
@adleong it looks like that exception did show up around the time we saw the issue. Full trace:
```
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23) 	at java.lang.Thread.run(Thread.java:748) Caused by: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem 	at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:648) 	at io.netty.internal.tcnative.SSL.readFromSSL(Native Method) 	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:482) 	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1020) 	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1127) 	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:210) 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1215) 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1127) 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162) 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) 	... 18 more Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397) 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302) 	at sun.security.validator.Validator.validate(Validator.java:260) 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281) 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136) 	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:221) 	at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:644) 	... 28 more Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392) 	... 35 more
```
DigiCert in the keystore on the proxy:
```
# keytool -list -rfc -storepass changeit -keystore $JAVA_HOME/lib/security/cacerts | grep -i digicert
Alias name: debian:digicert_trusted_root_g4.pem
Alias name: debian:digicert_global_root_g2.pem
Alias name: debian:digicert_assured_id_root_ca.pem
Alias name: debian:digicert_assured_id_root_g3.pem
Alias name: debian:digicert_high_assurance_ev_root_ca.pem
Alias name: debian:digicert_assured_id_root_g2.pem
Alias name: debian:digicert_global_root_ca.pem
Alias name: debian:digicert_global_root_g3.pem
```

**Comment by adleong** [comment]
@mrezaei00 to be honest, I'm pretty stumped.  That error message means that the client Linkerd was not able to validate the server's certificate.  In particular, it wasn't able to find a certificate chain back to a trusted root.  But, based on the keytool command you ran above, it seems like DigiCert High Assurance EV Root CA _is_ a trusted root.

I'm not able to reproduce this, even when using Linkerd to make requests to servers that use that same root cert such as wepay.com.  For example with this Linkerd config:

```
namers: []

routers:
- protocol: http
  dtab: /svc/* => /$/inet/wepay.com/443
  servers:
  - port: 4140
    ip: 0.0.0.0
  client:
    tls:
      commonName: wepay.com
```

I am able to `curl -v localhost:4140` and have the request successfully go through to wepay.com which also has a cert issued by DigiCert High Assurance EV Root CA.
