### ISSUE TITLE
Namerd interpreter_state diagnostics unavailable if used with a transformer

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd#1999]
If the Namerd interpreter is used with a transformer, the interpreter_state diagnostics endpoint will not be available.  This is because the transformer wraps the interpreter but does not expose the admin handlers of the underlying interpreter.

E.g.

```
     interpreter:
        kind: io.l5d.namerd
        dst: /$/inet/namerd/4100
        namespace: default
        transformers:
        - kind: io.l5d.k8s.daemonset
          namespace: test
          port: incoming
          service: l5d
```
