### ISSUE TITLE
Detect protocols based on request header

### ISSUE THREAD

**Issue by utrack** [linkerd/linkerd#2008]
Issue Type:

- [ ] Bug report
- [x] Feature request

Right now we need separate routers on different ports to process requests of different protocols.
Maybe we could run a single proxy for multiple routers if declared port for one overlaps with the other, and detect the protocol type based on a header of a request?

i.e.

```
- label: http-incoming
  protocol: http
  interpreter:
    kind: io.l5d.namerd
    dst: /#/io.l5d.k8s/linkerd/thrift/namerd
    namespace: incoming
  servers:
  - port: 4141
    ip: 0.0.0.0

- label: h2-incoming
  protocol: h2
  interpreter:
    kind: io.l5d.namerd
    dst: /#/io.l5d.k8s/linkerd/thrift/namerd
    namespace: incoming
  servers:
  - port: 4141
    ip: 0.0.0.0
```
Proxy on port 4141 should accept HTTP and H2 requests, detecting a protocol based on headers.
It definitely can be done, see https://github.com/soheilhy/cmux
