### ISSUE TITLE
l5d-add-context: Invalid argument is returned

### ISSUE THREAD

**Issue by utrack** [linkerd/linkerd#2014]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
I've tried to do a TRACE request with l5d-add-context as per tweet to debug one of my routes, but I've got 
`Invalid argument: /0.0.1.187:80 at remote address: /0.0.1.187:80. Remote Info: Not Available` as a response.

**What you expected to happen**:
Dtab tracing returned in the body

**How to reproduce it (as minimally and precisely as possible)**:
From a container:
`curl google.com:443 -XTRACE -H"l5d-add-context:1"`

**Anything else we need to know?**:
dtab:
```
[
  {
    "prefix": "/ph",
    "dst": "/$/io.buoyant.rinet"
  },
  {
    "prefix": "/svc",
    "dst": "/ph/80"
  },
  {
    "prefix": "/svc",
    "dst": "/$/io.buoyant.porthostPfx/ph"
  },
  {
    "prefix": "/k8s",
    "dst": "/#/io.l5d.k8s/bx"
  },
  {
    "prefix": "/managed",
    "dst": "/#/psvc"
  },
  {
    "prefix": "/managed/catalog-api/default",
    "dst": "/managed/catalog-api/ver/catalog-api-bx-357"
  },
  {
    "prefix": "/host",
    "dst": "/#/msvc"
  },
  {
    "prefix": "/host/k8s",
    "dst": "/host"
  },
  {
    "prefix": "/svc",
    "dst": "/$/io.buoyant.http.domainToPathPfx/host"
  },
  {
    "prefix": "/svc/82",
    "dst": "/svc"
  },
  {
    "prefix": "/svc",
    "dst": "/$/io.buoyant.porthostPfx/svc"
  }
]
```
**Environment**:
- linkerd/namerd version, config files: v1.4.3

**Comment by dadjeibaah** [comment]
Thanks for filing this issue @utrack. It looks like something special is going on when Linkerd is handling HTTPS traffic that prevents the header from being propagated. We will look into this.

**Comment by dadjeibaah** [comment]
@utrack we tried reproducing this issue and we do not run into it when we set up client TLS on the router that is configured with egress. Do you have client TLS set up in your config?

**Comment by utrack** [comment]
Can you point me to the right direction please @dadjeibaah ?
All I have for TLS specifically is this part:
```
    routers:
    - label: http-outgoing
      protocol: http
      interpreter:
        kind: io.l5d.namerd
        dst: /#/io.l5d.k8s/linkerd/thrift/namerd
        namespace: outgoing
      servers:
      - port: 4140
        ip: 0.0.0.0
      service:
        responseClassifier:
          kind: io.l5d.http.retryableRead5XX
      client:
        kind: io.l5d.static
        configs:
        # Use HTTPS if sending to port 443
        - prefix: "/$/io.buoyant.rinet/443/{service}"
          tls:
            commonName: "{service}"
```
