### ISSUE TITLE
How to convert the discovery(by k8s service) to Linkerd?

### ISSUE THREAD

**Issue by Aavon** [linkerd/linkerd#2026]
I used k8s Service to do the discovery business.After I learnd about Linkerd,I very much hope to integrate linkerd into the existing framework. 

I add the following config to the k8s yaml:

```
env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: http_proxy
            value: $(NODE_NAME):4340

``` 

appearance：

all request return timeout.

other info:

Our project is base on micro(github.com/micro),gRPC

Kubernetes:
   
   minikube

And I find kubectl container logs:

I0629 10:12:56.379242       1 logs.go:41] httputil: ReverseProxy read error during body copy: context canceled
I0629 10:14:00.449062       1 logs.go:41] httputil: ReverseProxy read error during body copy: context canceled
I0629 10:14:39.561378       1 logs.go:41] httputil: ReverseProxy read error during body copy: context canceled
I0629 10:14:39.561999       1 logs.go:41] httputil: ReverseProxy read error during body copy: context canceled
I0629 10:14:50.198338       1 logs.go:41] httputil: ReverseProxy read error during body copy: context canceled
I0629 10:15:02.762167       1 logs.go:41] httputil: ReverseProxy read error during body copy: context canceled

**Comment by dadjeibaah** [comment]
Hi @Aavon, because minikube doesn't have external load balancer support, you cannot use the `NODE_NAME` environment variable provided by the k8s Downward API. Instead, you can replace the `NODE_NAME` environment variable with a `HOST_IP` env. It would look something like this in your k8s yaml.

```yaml
- name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: http_proxy
            value: $(HOST_IP):4340
```

I think that should do the trick. Do let us know if that fixes it. Thanks!
