### ISSUE TITLE
Add config param to disable the /admin/shutdown endpoint

### ISSUE THREAD

**Issue by robertpanzer** [linkerd/linkerd#2033]
Issue Type:

- [ ] Bug report
- [x] Feature request

**What happened**:

Currently it is possible to shutdown any Linkerd instance by simple posting to the `/admin/shutdown` endpoint.
While I can imagine that many scenarios appreciate this behavior, it might not always be the case and could lead to a decrease in availability if attackers repeatedly post to this endpoint.

**What you expected to happen**:

It would be nice to have a configuration parameter that allows to disable this endpoint.

**How to reproduce it (as minimally and precisely as possible)**:

Start Linkerd locally and run the following command:

```
$ curl -v -X POST localhost:9990/admin/shutdown
```

Linkerd will shut down asap.

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files: Latest version, any config that enables the admin server
- Platform, version, and config files (Kubernetes, DC/OS, etc): OS X
- Cloud provider or hardware configuration:

**Comment by robertpanzer** [comment]
I could try to create a PR for this feature in case it is considered worth to be added.
Would it make sense to simply have a parameter `enableShutdown` or so with default `true` that allows to disable this endpoint?

```yaml
admin:
  port: 9990
  ip: 0.0.0.0
  shutdownEnabled: false
```

Or should there be a more general approach that would allow to disable any admin endpoint by defining a blacklist?

```yaml
admin:
  port: 9990
  ip: 0.0.0.0
  endpointBlackList:
  - /admin/shutdown
  - /admin/threads
```

What do you think?
