### ISSUE TITLE
Linkerd Header Token as ASCII bytes not UTF-8

### ISSUE THREAD

**Issue by a4chet** [linkerd/linkerd#2036]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
I am trying to write a golang proxy that can dynamically route grpc requests using linkerd + consul. 
I am using Linkerd's H2 protocol with the `io.l5d.header.token` identifier with a custom header token.  I am adding the custom header in the golang program using `grpc-go\metadata`

I believe go is encoding the metadata header as `ASCII` text but Linkerd is interpreting the bytes as `UTF8`. I see the following error in Linkerd:
`HTTP/2 Header Token Identifier
com.twitter.finagle.naming.buoyant.RichNoBrokersAvailableException: Unable to route request!
linkerd_1     | service name: /svc/\x2f\x73\x76\x63\x2f\x73\x79\x73\x74\x65\x6d\x2f\x65\x78\x61\x6d\x70\x6c\x65\x63\x6f\x6d\x2e\x6c\x69\x62\x72\x61\x72\x79\x2e\x55\x73\x65\x72\x53\x65\x72\x76\x69\x63\x65\x2f\x4c\x6f\x67\x69\x6e\x55\x73\x65\x72-
`

**What you expected to happen**:
I expect Linkerd to handle ASCII encoding of the header token value. I believe it is currently assuming the value is UTF8 encoded from [HeaderTokenIdentifyer.scala](https://github.com/linkerd/linkerd/blob/c5a3b42f7d8fac76d8b8928ff9a369e803fe7be7/linkerd/protocol/h2/src/main/scala/io/buoyant/linkerd/protocol/h2/HeaderTokenIdentifier.scala#L41)

**How to reproduce it (as minimally and precisely as possible)**:
1. Clone https://github.com/improbable-eng/grpc-web
2. Add a new metadata header to the metadata in [\go\grpcwebproxy\main.go](https://github.com/improbable-eng/grpc-web/blob/72eb701d6f320ca324b3347c7925a720b553eae5/go/grpcwebproxy/main.go#L109) 
`mdCopy["test-header"]=[]string{"/svc/test"}`
3. Update linkerd config yml to use header token identifier with "test-header"

**Anything else we need to know?**:
* I am not sure why the pseudo headers (":") are UTF8 encoded, but normal headers are not...

**Environment**:
- linkerd/namerd version, config files:
`1.4.2`
```
- protocol: h2
  label: grpc_web_proxy-to-svc
  client:
    tls:
      commonName: localhost
      clientAuth:
        certPath: C:/linkerd/certs/localhost.crt
        keyPath: C:/linkerd/certs/localhost.key
  experimental: true
  interpreter:
    kind: io.l5d.mesh
    experimental: true    
    dst: /$/inet/namerd/4100
    root: /proxy2svc
    tls:
      commonName: localhost
      clientAuth:
        certPath: C:/linkerd/certs/localhost.crt
        keyPath: C:/linkerd/certs/localhost.key
  identifier:
    kind: io.l5d.header.token
    header: test-header
#    kind: io.l5d.header.path
#    segments: 2
  servers:
  - port: 10001
    ip: 0.0.0.0
    tls:
      certPath: C:/linkerd/certs/localhost.crt
      keyPath: C:/linkerd/certs/localhost.key

```
- Platform, version, and config files (Kubernetes, DC/OS, etc): 
Docker for Win on Windows 10

- Cloud provider or hardware configuration:
Windows 10 Docker, using Nanoserver
