### ISSUE TITLE
Breaking change in configuration for grpc-response-classifier

### ISSUE THREAD

**Issue by msiebeneicher** [linkerd/linkerd#2075]
Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:

Since version 1.4.5 the grpc-response-classifier `io.l5d.h2.grpc.Default` ends up in an exception if you configure it like the documentation in lowercase.

**What you expected to happen**:

No exception by using `io.l5d.h2.grpc.default`

**How to reproduce it (as minimally and precisely as possible)**:

Failing config snippet:

```yaml
routers:
  - protocol: h2
    [...]
    service:
      responseClassifier:
        kind: io.l5d.h2.grpc.default
```

Working config snippet:

```yaml
routers:
  - protocol: h2
    [...]
    service:
      responseClassifier:
        kind: io.l5d.h2.grpc.Default
```

**Anything else we need to know?**:

Commit of the issue: https://github.com/linkerd/linkerd/commit/df5294e33fd35789c0238226bd9665a7151d1ae8

Documentation: https://linkerd.io/config/1.4.5/linkerd/index.html#grpc-response-classifiers
