### ISSUE TITLE
Please help zookeeper configuration 

### ISSUE THREAD

**Issue by dhruvmphatek** [linkerd/linkerd#2076]
Need help
We are getting this error
Failure(ChannelException at remote address: localhost/127.0.0.1:8080. Remote Info: Not Available, flags=0x05) with RemoteInfo -> Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: localhost/127.0.0.1:8080, Downstream label: interpreter/io.l5d.namerd.http, Trace Id: fe1fcc03bcbd8ac3.831475bc361b6de9<:fe1fcc03bcbd8ac3

My Configuration is: 

```
admin:
    port: 9990
    ip: 0.0.0.0

namers:
- kind: io.l5d.zkLeader
  zkAddrs:
  - host: 192.168.0.90
    port: 2181

routers:
- protocol: http
  interpreter:
    kind: io.l5d.namerd.http
    dst: /$/inet/localhost/8080
    experimental: true
    transformers:
    - kind: io.l5d.port
      port: 8080
  announcers:
  - kind: io.l5d.serversets
    zkAddrs:
    - host: 192.168.0.90
      port: 2181
    pathPrefix: /icx
  dtab: |
   /svc => /#/io.l5d.serversets/arpit;
  httpAccessLog: logs/access.log
  label: int
  servers:
  - port: 4140
    ip: 0.0.0.0
    announce:
     - /#/io.l5d.serversets/arpit
```
