### ISSUE TITLE
L5d fails with DynBoundTimeoutException after target service is updated

### ISSUE THREAD

**Issue by ylopatin-earnin** [linkerd/linkerd#2079]
# Thanks for your help improving the project! #

## Getting Help ##

Github issues are for bug reports and feature requests. For questions about
Linkerd, how to use it, or debugging assistance, start by
[asking a question in the forums](https://discourse.linkerd.io/) or join us on
[Slack](https://slack.linkerd.io/).

Full details at [CONTRIBUTING.md](https://github.com/linkerd/linkerd/blob/master/CONTRIBUTING.md).

## Filing a Linkerd issue ##

Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
When  k8s deployment is applied and new version is installed, L5d fails with "E 0720 15:10:25.148 UTC THREAD10: service failure: com.twitter.finagle.naming.buoyant.DynBoundTimeoutException: Exceeded 10.seconds binding timeout while connecting to /#/io.l5d.k8s/default/http/_my_service_name_ for name: /svc/_my_service_name_"

**What you expected to happen**:
L5d should update new service endpoints and send traffic to new pods

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
k8s deployed l5d and target service
servers config for usedroute:
```
  servers:
  - port: XXXX
    ip: 0.0.0.0
    clearContext: true
  bindingCache:
    paths: 100
    trees: 100
    bounds: 100
    clients: 10
    idleTtlSecs: 5
```
rollingupdate details:
```
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 50%
  minReadySeconds: 20
```

**Environment**:
- linkerd/namerd version, config files: 1.4.2
- Platform, version, and config files (Kubernetes, DC/OS, etc): kubernetes in AWS (not EKS)
- Cloud provider or hardware configuration:

[same issue was in December](https://github.com/linkerd/linkerd/issues/1730)

**Comment by adleong** [comment]
Thanks for the report, @ylopatin-earnin!  This error message means that Linkerd was not able to establish a connection to your service for some reason.  Are there any other errors in the Linkerd logs that could explain the problem?  It may also be helpful to use tcpdump to see if something is preventing the TCP handshake from occurring.

**Comment by ylopatin-earnin** [comment]
Logs says
``
E 0802 12:29:17.319 UTC THREAD29: service failure: Failure(No route to host: /100.96.7.223:80 at remote address: /100.96.7.223:80. Remote Info: Not Available, flags=0x09) with RemoteInfo -&gt; Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /100.96.7.223:80, Downstream label: #/io.l5d.k8s/default/http/{{MY_SERVICENAME}}, Trace Id: 941d1dae33b973cf.941d1dae33b973cf&lt;:941d1dae33b973cf
``
where 100.96.7.223 - ip of previous pod
After deployment l5d still connects to old ip

**Comment by ylopatin-earnin** [comment]
@adleong thank you for quick update
Following info is attached:
- linkerd `/namer_state/io.l5d.k8s.json`  responses  before and after deployment (`before_deployment_io.l5d.k8s.json.log` and `after_deployment_io.l5d.k8s.json.log`)
- kubernetes `/api/v1/namespaces/default/endpoints/gateway` responses  before and after deployment (`before_deployment_k8s_api.json.log` and `after_deployment_k8s_api.json.log`)



[after_deployment_k8s_api.json.log](https://github.com/linkerd/linkerd/files/2256852/after_deployment_k8s_api.json.log)
[before_deployment_io.l5d.k8s.json.log](https://github.com/linkerd/linkerd/files/2256853/before_deployment_io.l5d.k8s.json.log)
[before_deployment_k8s_api.json.log](https://github.com/linkerd/linkerd/files/2256854/before_deployment_k8s_api.json.log)
[after_deployment_io.l5d.k8s.json.log](https://github.com/linkerd/linkerd/files/2256855/after_deployment_io.l5d.k8s.json.log)

**Comment by adleong** [comment]
Thanks for the logs, @ylopatin-earnin.  In those logs I don't see `100.96.7.223` either before or after the deployment.  Which is the pod ip that Linkerd is erroneously routing to?  From what I can tell, Linkerd looks to be perfectly in sync with the Kubernetes API.

**Comment by ylopatin-earnin** [comment]
'100.96.7.223' was in initial logs, logs files attached are 1 day after.
1 day - several l5d restarts, so it is expected that first IP is not found in logs

Please look only to 4 files attached, they describe behavior right before and after deployment
Thing i want to show is screenshoted:
![image](https://user-images.githubusercontent.com/34706053/43684334-0c7dd99a-98a7-11e8-810e-4e684cc26381.png)

**Comment by adleong** [comment]
Hi @ylopatin-earnin 

Thanks for the clarification.  This is a bit confusing but since the Kubernetes API is a streaming API, we track the last initial response body separately from the streaming data.  Therefore we would expect the "response" field to be the same before and after the deploy (assuming the Kubernetes stream was not reset) but the "lastStreamData" fields to be different and for the "lastStreamData" after the deploy to contain the new set of endpoints.

**Comment by ylopatin-earnin** [comment]
@adleong  thanks for answers

is it bug of feature?
how could i leverage this case to have l5d cache totally updated after k8s service deployment?

**Comment by adleong** [comment]
Ah, that's great, that means that Linkerd DID get the endpoints update from Kubernetes.  The next thing to look at is the `/client_state.json` endpoint on the Linkerd admin server.  This shows the internal state of Linkerd's load balancers and contains the addresses that Linkerd uses for routing.

**Comment by ylopatin-earnin** [comment]
`/client_state.json` is not updated after deployment, staying same as before.
Only pod restart wipes old data from gateway client

**Comment by lgmyrek** [comment]
@adleong  I'm suffering from similar issue, observed for now only with replicas >= 2

**Comment by ylopatin-earnin** [comment]
@lgmyrek can you share more details?
k8s cluster version?  what tool or cloud used?
is it in AWS?

thanks

**Comment by adleong** [comment]
@ylopatin-earnin hmmmm that's pretty weird that the k8s namer state shows that it has the correct current value but this value isn't propagated to the client state.  I've never seen that happen before.  Do you have a concrete set of steps that we can use to reproduce this?

**Comment by lgmyrek** [comment]
@ylopatin-earnin
bare metal, 1.10

**Comment by ylopatin-earnin** [comment]
@adleong  as my provider is AWS, other guy's is bare metal, my linkerd  is also 1.4.5, but i saw that problem even on 1.3.7. So, i do not think it is k5d version or provider specific error
May be wrong configuration,
I can share my configs, may be there is an issue:

[l5d-configmap-main-yaml.txt](https://github.com/linkerd/linkerd/files/2284142/l5d-configmap-main-yaml.txt)

**Comment by adleong** [comment]
Ok thanks.  We have not been able to reproduce this so far but we're going to spend some more time trying to get a reproduction.  Any detailed reproduction steps would be extremely helpful.

**Comment by ylopatin-earnin** [comment]
1. configure router like this

```
admin:
  ip: 0.0.0.0
  port: 9990
  
usage:
  orgId: linkerd-daemonset

namers:
- kind: io.l5d.k8s
  host: localhost
  port: 8001  
- kind: io.l5d.rewrite
  prefix: /portNsSvcToK8s
  pattern: "/{port}/{ns}/{svc}"
  name: "/k8s/{ns}/{port}/{svc}"   
  
routers:
- protocol: http
  label: http-ingress
  client:
    failureAccrual:
      kind: none
  identifier:
    kind: io.l5d.path
    consume: true        
  interpreter:
    kind: io.l5d.k8s.configMap
    experimental: true
    name: l5d-dtabs-config
    filename: http-ingress
    namespace: servicemesh
  servers:
  - port: 4142
    ip: 0.0.0.0
    clearContext: true
  bindingTimeoutMs: 30000
  bindingCache:
    idleTtlSecs: 1
```
and dtab for it
```
/svc       => /#/io.l5d.k8s/default/http/gateway;
```

Deploy any service to default namespace, port http and name 'gateway'
try redeploy it
and access via linkerd
