### ISSUE TITLE
K8s Services pointing external services/IPs can't be routed by namerd

### ISSUE THREAD

**Issue by bdlk** [linkerd/linkerd#2089]
Issue Type:
- [X] Bug report
- [ ] Feature request

**What happened**:
K8s Services pointing external services/IPs can't be routed by namerd.

**What you expected to happen**:
Service mesh should cover a traffic to external services.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a service

```
---
apiVersion: v1
kind: Service
metadata:
  name: xxx
  labels:
    name: xxx
spec:
  type: ClusterIP
  selector: {}
  ports:
    - name: "xxx"
      protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 0
---
apiVersion: v1
kind: Endpoints
metadata:
  name: xxx
  labels:
    name: xxx
subsets:
  - addresses:
      - ip: {{ .Values.xxx.targetIp }}
    ports:
      - name: "mysql"
        port: {{ .Values.xxx.targetPort }}
---
```

2. login to pod in the cluster.
3. `curl xxx` (works)
4. `export HTTP_PROXY=l5d.test.svc.cluster.local:4140`
5. `curl xxx`
output:

```
Unable to route request!

service name: /svc/xxx
resolutions considered:
  /#/io.l5d.k8s/test/http/xxx (neg)
dtab:
  /srv => /#/io.l5d.k8s/test/http
  /host => /srv
  /tmp => /srv
  /svc => /host
base dtab:

override dtab:

```
![screenshot from 2018-08-01 12-21-48](https://user-images.githubusercontent.com/6249310/43524964-dc5c443a-95a0-11e8-959f-0be0fc66564c.png)

Other services works like a charm
![screenshot from 2018-08-01 12-22-08](https://user-images.githubusercontent.com/6249310/43524966-dc7b786e-95a0-11e8-91d4-dfd00a19fa60.png)

I've observed same behave with Services like this:
```
---
kind: Service
apiVersion: v1
metadata:
  name: xxx
spec:
  type: ExternalName
  externalName: "google.com"
---
```

**Environment**:
- linkerd & namerd version 1.4.5
- Kubernetes
