### ISSUE TITLE
Misleading config documentation for trustCerts and trustCertsBundle

### ISSUE THREAD

**Issue by mrezaei00** [linkerd/linkerd#2090]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
Warning from Linkerd `1.4.4` when used with the `trustCerts` config:
```
W 0718 19:01:18.367 UTC THREAD1: trustCerts configuration option is deprecated, please consider using trustCertsBundle
```
The config documentation prior to `1.4.5` does not mention `trustCertsBundle`, and `1.4.5` configs don't seem to be in-sync with `1.4.4` code:

![image](https://user-images.githubusercontent.com/7763122/43533517-d2d0b0d6-9569-11e8-9906-5f3a1eb91f77.png)

I assumed the deprecation notice on `trustCertsBundle` is meant for `trustCerts`, but is `trustCertsBundle` also a list or only allowing a single CA?

> trustCertsBundle:	A list of file paths of CA certs to use for common name validation (deprecated, please use trustCertsBundle).

Example from the same config docs:
```
routers:
- protocol: http
  client:
    tls:
      commonName: linkerd.io
      trustCertsBundle: /certificates/cacert.pem
      clientAuth:
        certPath: /certificates/cert.pem
        keyPath: /certificates/key.pem
      protocols:
      - TLSv1.2
```

**What you expected to happen**:
`trustCerts` to be marked as deprecated in the config docs as well, and `trustCertsBundle` default value and description to be inline with the examples in the same doc.

**How to reproduce it (as minimally and precisely as possible)**:
Run Linkerd `1.4.4` with `trustCerts` config to get the warning, and use [`1.4.5` config docs](https://linkerd.io/config/1.4.5/linkerd/index.html#client-tls) to see the config description mis-match.

**Environment**:
- linkerd/namerd version, config files:
```
      client:
        tls:
          commonName: "tls_common_name"
          trustCerts:
          - certificates/service-mesh-ca
...
      servers:
        tls:
          certPath: certificates/self-sgned-cert
          keyPath: certificates/self-sgned-key
...
```
- Platform, version, and config files (Kubernetes, DC/OS, etc): Kubernetes 1.10
- Cloud provider or hardware configuration: GCP
