### ISSUE TITLE
Client latency degrades suddenly

### ISSUE THREAD

**Issue by zackangelo** [linkerd/linkerd#2115]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:

We've noticed client latencies degrade suddenly and haven't been able to pin down why. Here's an example of this happening on a production node: 
![image](https://user-images.githubusercontent.com/688990/44888273-05a30e00-ac85-11e8-8abf-426d68026357.png)

At around 16:00 the latency suddenly spiked from the perspective of the client-side linkerd in a linkerd-to-linkerd setup (we call this router `h2-out`). There was not a corresponding spike on the service-side linkerd (we call this router `h2-in`). At around 19:00 towards the end of the displayed time range, we restarted linkerd holding every else constant and the latencies dropped to pre-16:00 levels. 

I pulled the GC logs from that node and noticed a slight uptick in Full GC frequency, not not enough to explain the increased latency (times are offset forward by 2 hours): 

![image](https://user-images.githubusercontent.com/688990/44888628-02108680-ac87-11e8-9a05-e67421a7cc4e.png)

**What you expected to happen**:

Latencies to remain constant and not degrade.

**How to reproduce it (as minimally and precisely as possible)**:

Don't know yet. 

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files: 1.4.5/1.4.5. 

router config: 

```
  # http 2: service -> [linkerd] -> linkerd -> service
  # should lookup consul service then rewrite outgoing port to linkerd
  - label: h2-out
    protocol: h2
    experimental: true
    servers:
      - port: 4142
        ip: 169.254.1.1
        initialStreamWindowBytes: 1048576
        maxFrameBytes: 4194304
    client:
      initialStreamWindowBytes: 1048576
      maxFrameBytes: 4194304
      hostConnectionPool:
        minSize: 8
      failureAccrual:
        kind: none
      tls:
        commonName: linkerd.service.consul
        trustCerts: [/etc/linkerd/ca.crt]
    identifier:
      kind: io.l5d.header.path
      segments: 1
    interpreter:
      kind: io.l5d.mesh
      experimental: true
      dst: /#/io.l5d.consul/.local/namerd-grpc
      root: /h2
      transformers:
        - kind: io.l5d.port
          port: 4143

  # http 2: service -> linkerd -> [linkerd] -> service
  # should lookup local service then filter down to local node
  - label: h2-in
    protocol: h2
    experimental: true
    client:
      initialStreamWindowBytes: 1048576
      maxFrameBytes: 4194304
      failureAccrual:
        kind: none
      hostConnectionPool:
        minSize: 8
    servers:
      - port: 4143
        ip: 10.177.82.223
        initialStreamWindowBytes: 1048576
        maxFrameBytes: 4194304
        tls:
          certPath: /etc/linkerd/server.crt
          keyPath: /etc/linkerd/server.crt
          ciphers:
            - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
            - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
            - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
            - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
            - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
            - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
            - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
            - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
            - TLS_RSA_WITH_AES_128_GCM_SHA256
            - TLS_RSA_WITH_AES_256_GCM_SHA384
    identifier:
      kind: io.l5d.header.path
      segments: 1
    interpreter:
      kind: io.l5d.mesh
      experimental: true
      dst: /#/io.l5d.consul/.local/namerd-grpc
      root: /h2
      transformers:
        - kind: io.l5d.localhost
```
- Platform, version, and config files (Kubernetes, DC/OS, etc): Nomad 
- Cloud provider or hardware configuration: Bare metal
