### ISSUE TITLE
Expose DaemonSet transformer state

### ISSUE THREAD

**Issue by negz** [linkerd/linkerd#2149]
Issue Type: Feature request

**What happened**: I run linkerd on Kubernetes in linker to linker mode. For whatever reason the Kubernetes `kube-system/l5d` service linkerd uses in my deployment to discover the pods in its DaemonSets (to route downstream traffic) had a stale and inaccurate set of pods. You can see more in #2148. This was not a linkerd bug, but might have been easier to debug if it were possible to inspect linkerd's DaemonSet transformer state in the same way we can inspect the Kubernetes namer state today.

**What you expected to happen**:
An endpoint such as `http://:9990/transformer_state/io.l5d.k8s.daemonset.json` exposes linkerd's current view of each DaemonSet namer. (I suppose it may make sense to nest this under namer_state somehow?)

Perhaps there would also be value in exposing the localnode transformer state? My understanding is that one doesn't actually make any separate calls to the Kubernetes API, so I usually feel I can infer the localnode transformer state from the namer state. That said, more visibility can't hurt.

**Anything else we need to know?**: Here's my DaemonSet transformer configuration:

```yaml
- kind: io.l5d.k8s
  prefix: /io.l5d.k8s.http
  transformers:
  - kind: io.l5d.k8s.daemonset
    namespace: kube-system
    port: http-incoming
    service: l5d
    hostNetwork: true
```

**Environment**:
- linkerd/namerd version, config files: 1.4.6
- Platform, version, and config files (Kubernetes, DC/OS, etc): Kubernetes
- Cloud provider or hardware configuration: GCP
