### ISSUE TITLE
Namerd memory leak

### ISSUE THREAD

**Issue by adw12382** [linkerd/linkerd#2212]
Creating this issue as a follow-up regarding the discussions with @dadjeibaah in slack channel.

Issue Type:
- [ ] Bug report

**What happened**:
Namerd's memory usage keeps increasing and will not perform garbage collection until its usage hit 80%~100%. A possible consequence is that, if the GC cannot be finished properly, the n4d pods will unable to serve any requests unless it's restarted. A side fact is that, linkerd's memory usuage has ever gone up higher than 20%, which might mean Namerd is not releasing the objects/resources properly which caused a memory leak.

Namerd Memory Usage Flow
![screen shot 2019-01-28 at 1 59 43 pm](https://user-images.githubusercontent.com/46726793/51870987-001c2380-230a-11e9-82fb-c8dcd8102d0e.png)

Linkerd Memory Usage Flow
![screen shot 2019-01-28 at 1 58 33 pm](https://user-images.githubusercontent.com/46726793/51870999-07433180-230a-11e9-9a45-48e4e2098636.png)
 
**What you expected to happen**:
Namerd's memory usage flow should be similar to what it's shown for Linkerd.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files:
Namerd:1.6.0

Namerd config file
```
admin:
  ip: 0.0.0.0

telemetry:
- kind: io.l5d.prometheus
  prefix: l5d_n4d_

storage:
  kind: io.l5d.zk
  pathPrefix: /dtabs
  zkAddrs:
  - host: hostname1
    port: 2181
  - host: hostname2
    port: 2181
  - host: hostname3
    port: 2181

namers:
- kind: io.l5d.k8s
  prefix: -
  host: 127.0.0.1
  port: 8001
  transformers:
  - kind: io.l5d.k8s.daemonset
    namespace: mesh
    k8sHost: 127.0.0.1
    k8sPort: 8001
    port: in-http
    service: l5d
- kind: io.l5d.k8s
  prefix: -
  host: 127.0.0.1
  port: 8001
  transformers:
  - kind: io.l5d.k8s.daemonset
    namespace: mesh
    k8sHost: 127.0.0.1
    k8sPort: 8001
    port: in-grpc
    service: l5d
- kind: io.l5d.k8s
  prefix: -
  host: 127.0.0.1
  port: 8001

interfaces:
- kind: io.l5d.mesh
  ip: 0.0.0.0
  port: 4321
- kind: io.l5d.httpController
  ip: 0.0.0.0
  port: 4180
```

- Platform, version, and config files (Kubernetes, DC/OS, etc):
Kubernetes

**Comment by edio** [comment]
```
interfaces:
- kind: io.l5d.mesh
  ip: 0.0.0.0
  port: 4321
- kind: io.l5d.httpController
  ip: 0.0.0.0
  port: 4180
```

@adw12382 , which of these interfaces you use the most?
We also observe namerd memory leak in our environment, but our namerd config is very different and even includes custom plugins. Only the `interfaces` secion is the same. So I wonder, how your usage is similar to ours.
