### ISSUE TITLE
[Question][Feature] Provide way of supplying Allowed/Denied list of domains when running as egress.

### ISSUE THREAD

**Issue by gabrielcalderon** [linkerd/linkerd#2270]
Issue Type:

- [ ] Bug report
- [X ] Feature request

**Environment**:
- linkerd/namerd version, config files:

```
admin:
  ip: 0.0.0.0
  port: 9990

routers:
- protocol: http
  dtab: |
      /ph        => /$/io.buoyant.rinet ; # Lookup the name in DNS
      /srv       => /ph/80 ; # Use port 80 if unspecified
      /srv       => /$/io.buoyant.porthostPfx/ph ; # Attempt to extract the port from the hostname
  servers:
  - ip: 0.0.0.0
    port: 8080
  service:
    responseClassifier:
      kind: io.l5d.http.retryableRead5XX
  client:
    kind: io.l5d.static
      configs:
      - prefix: "/$/io.buoyant.rinet/*/{hostname}"
          tls:
            commonName: "{hostname}"
```

- Platform, version, and config files (Kubernetes, DC/OS, etc): Docker
- Cloud provider or hardware configuration: On-Premises, Ubuntu LTS

My question/feature request is: Does Linkerd provide a way to supply a list of allowed hostnames for this kind of egress forward HTTP/HTTPS proxies?

Using this configuration I can do HTTP/HTTPS curl requests using Linkerd, even thou the HTTPS don't show up in the UI, the HTTP ones show up fine every time a request is made. 

Given that I'm running this in an on-premises airgap environment is there a way to provide Linkerd with a list of Allowed hostnames/domains/subdomains that it should allow to egress through the proxy? I can't seem to find a way of doing this looking at the API documentation.
