### ISSUE TITLE
HTTP router performance degrades over time

### ISSUE THREAD

**Issue by pliutak-nih** [linkerd/linkerd#2279]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**: We're observing l5d HTTP router performance degradation over time on our prod instances. It's possible that this issue is somehow related to  https://github.com/linkerd/linkerd/issues/2247 ~~because it reproduces **only** when native memory direct buffer is turned on~~.

**What you expected to happen**: Stable throughput of HTTP router over time.

**How to reproduce it (as minimally and precisely as possible)**:

1. Launch l5d:

``` bash
LOCAL_JVM_OPTIONS="-XX:MaxDirectMemorySize=64M -Dio.netty.noUnsafe=true" \
	./linkerd-1.6.3-exec linkerd.yaml &
```

linkerd.yaml:

``` yaml
admin:
  port: 9995

routers:
- protocol: http
  dtab: |
    /svc => /$/inet/127.1/9995;
  servers:
  - port: 4145

# this part is from https://github.com/linkerd/linkerd/issues/2247#issuecomment-478338189
- protocol: h2
  h2AccessLog: logs/access.log
  h2AccessLogRollPolicy: daily
  h2AccessLogAppend: true
  h2AccessLogRotateCount: -1
  dtab: |
    /svc => /$/inet/127.1/9999;
  identifier:
    kind: io.l5d.header.token
    header: ":authority"
  servers:
  - port: 4150
    maxConcurrentStreamsPerConnection: 300
    addForwardedHeader:
      by: {kind: "ip:port"}
      for: {kind: "ip:port"}
    initialStreamWindowBytes: 1048576 # 1MB
  client:
    initialStreamWindowBytes: 1048576 # 1MB
```

2. Launch jmeter infinite scenario against HTTP router:

``` bash
jmeter -n -t local_l5d_4145.jmx
```

[local_l5d_4145.jmx.txt](https://github.com/linkerd/linkerd/files/3263416/local_l5d_4145.jmx.txt)

3. Launch server and client from https://github.com/linkerd/linkerd/issues/2247#issuecomment-478338189 in the background to put some load on H2 router:

server:
``` bash
java -Dlogback.configurationFile=logback.xml \
	-Djava.util.logging.config.file=logging.properties \
	-classpath deadliner.jar \
	com.bigcommerce.deadliner.DeadlinerServer &
```

client:
``` bash
java -Dlogback.configurationFile=logback.xml \
	-classpath deadliner.jar \
	com.bigcommerce.deadliner.DeadlinerClient \
	127.0.0.1 \
	4150 \
	20 \
	1000000 \
	1 &
```

**Summary**:

![image](https://user-images.githubusercontent.com/49652377/59065851-b2956180-887b-11e9-98b7-b5b8b13720e9.png)

**Environment**:
- linkerd version - 1.6.3
