### ISSUE TITLE
linkerd send traffic to retired servers

### ISSUE THREAD

**Issue by pengfei-xue** [linkerd/linkerd#2283]
# Thanks for your help improving the project! #

## Getting Help ##

Github issues are for bug reports and feature requests. For questions about
Linkerd, how to use it, or debugging assistance, start by
[asking a question in the forums](https://discourse.linkerd.io/) or join us on
[Slack](https://slack.linkerd.io/).

Full details at [CONTRIBUTING.md](https://github.com/linkerd/linkerd/blob/master/CONTRIBUTING.md).

## Filing a Linkerd issue ##

Issue Type:

- [ x] Bug report
- [ ] Feature request

**What happened**:
i'm using linkerd 1.4.6, we use namerd with consul to do service discovery, 
we added some new servers for one service, and retired some servers, 
updated configs in consul, some linkerd instances got the right addrs for that service, 
but some still sent traffic to the retired ip

use this namerd api `/api/1/resolve/gm?path=/svc/prod/gaia` get the right addrs
but call the linkerd api `/client_state.json` give me the wrong addrs(old retired addr returned).

**What you expected to happen**:
after update consul, linkerd instance should not send traffic to retired servers

**How to reproduce it (as minimally and precisely as possible)**:
don't know

**Anything else we need to know?**:

**Environment**:

linkerd/namerd version, config files:

```
     routers:
- protocol: http
  maxRequestKB: 51200
  label: gm-http
  httpAccessLog: /data/log/gm-linkerd/access.log
  httpAccessLogRollPolicy: daily
  httpAccessLogAppend: true
  httpAccessLogRotateCount: 1
  bindingTimeoutMs: 1000
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd.prod.gengmei/4100
    namespace: gm

  client:
    kind: io.l5d.global
    loadBalancer:
      kind: ewma
    failureAccrual:
      kind: io.l5d.consecutiveFailures
      failures: 10
```

```
      namers:
- kind: io.l5d.consul
  host: 127.0.0.1
  port: 8500
  includeTag: true
  useHealthCheck: false
  healthStatuses:
    - "passing"
    - "warning"
  setHost: false
  consistencyMode: stale
  failFast: true

storage:
  kind: io.l5d.consul
  host: 127.0.0.1
  port: 8500
  pathPrefix: /namerd/dtabs

interfaces:
- kind: io.l5d.thriftNameInterpreter
  ip: 0.0.0.0
  port: 4100

- kind: io.l5d.httpController
  ip: 0.0.0.0
  port: 4180
```

- Platform, version, and config files (Kubernetes, DC/OS, etc): linux vm centos7.5
- Cloud provider or hardware configuration:
