### ISSUE TITLE
Defaults for socketoptions stanza aren't applied if a partial config is supplied

### ISSUE THREAD

**Issue by taer** [linkerd/linkerd#2312]
If you have a linkerd.yaml file with the following servers config:
```
 servers:
  - port: 80
    ip: 0.0.0.0
    socketOptions:
      readTimeoutMs: 601000
      writeTimeoutMs: 601000
      keepAlive: true
      backlog: 128
``` 
the defaults are not applied correctly as stated in the docs:  https://api.linkerd.io/1.6.3/linkerd/index.html#socket-options

Here is the section from /config.json  for the above config:
```    
"port": 80,
"socketOptions": {
            "noDelay": false,
            "reuseAddr": false,
            "reusePort": false,
            "writeTimeoutMs": 601000,
            "readTimeoutMs": 601000,
            "keepAlive": true,
            "backlog": 128
},
```

We have a test patch ready, and will be submitting that later this afternoon.
