### ISSUE TITLE
Streaming is disabled if you do not set streamingEnabled in 1.7.0

### ISSUE THREAD

**Issue by taer** [linkerd/linkerd#2331]
With this config
```
routers:
- protocol: http
  label: cgp
  compressionLevel: 3
  maxHeadersKB: 16
  maxInitialLineKB: 18
  #streamingEnabled: true
  #streamAfterContentLengthKB: 5
```
in linkerd 1.7.0, the effective config is 
```
routers:
- protocol: http
  label: cgp
  compressionLevel: 3
  maxHeadersKB: 16
  maxInitialLineKB: 18
  streamingEnabled: false
  streamAfterContentLengthKB: 5120
```
The case statement that handled the enable steaming didn't honor the default if streamAfterContentLengthKB was not present. Also, the finangle default for streaming is 5M, not 5K as indicated in the docs. So I removed the dependence on finagle's default.
