### ISSUE TITLE
improve dtab documentation with some real-life examples

### ISSUE THREAD

**Issue by wmorgan** [linkerd/linkerd#320]
Based on some conversation in Slack, it might be useful to have some concrete examples of "good production dtabs" in the dtab documentation. 

There are probably some common starting points that people would use when actually constructing a dtab for their environment. (We ship with one.) 

For example:
- host-based routing for HTTP by looking up in Zookeeper
- host-based routing for HTTP by looking up in fs namer, falling back to Zookeeper
- path-based routing for HTTP?
- port-based routing for thrift?

**Comment by olix0r** [comment]
There are a ton of examples in https://linkerd.io/doc/latest/config, fwiw

**Comment by wmorgan** [comment]
I see a few non-trivial examples in config.md, but they're largely described in term os "how to use the X namer when I have it configured". Which is fine, that needs to be documented too.

I think there's still a gap between the generic/ice-cream doc, and "I have a working dtab for my config".

**Comment by JustinVenus** [comment]
Maybe it would be easier to explain delegations tables by showing another proxy configuration that uses linkerd as a backend and then show how a few utilities would work when a 'Dtab-Local' header is present. 

When I explain delegation tables to my peers I use a similiar linkerd.yaml and haproxy.cfg as a starting point.  (Disclaimer probably contains syntax errors)

### linkerd.yaml
```yaml
admin:
  port: 9990

namers:
- kind: io.l5d.consul
  experimental: true
  host: 127.0.0.1
  port: 8500

routers:
- protocol: http
  baseDtab: |
    /http/1.1/POST/localhost:10006 => /s/service6-write;
    /http/1.1/PUT/localhost:10006 => /s/service6-write;
    /http/1.1/DELETE/localhost:10006 => /s/service6-write;
    /http/1.1/* => /s;
    /s/localhost:10001 => /s/service1;
    /s/localhost:10002 => /s/service2;
    /s/localhost:10003 => /s/service3;
    /s/localhost:10004 => /s/service4;
    /s/localhost:10005 => /s/service5;
    /s/localhost:10006 => /s/service6-read;
    /s => /s#;
    /s# => /#/io.l5d.consul/cluster_1 | /#/io.l5d.consul/cluster_2;
  label: http-rpc
  dstPrefix: /http
  servers:
  - port: 4041
    ip: 0.0.0.0
```

### haproxy.cfg
```sh
global
        log 127.0.0.1   local0
        log 127.0.0.1   local1 notice
        stats socket /tmp/haproxy
        spread-checks 7
        maxconn 4096
        user haproxy
        group haproxy
        daemon

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        option  dontlog-normal
        retries 2
        option redispatch
        option httpclose
        maxconn 2000
        contimeout      5000
        clitimeout      50000
        srvtimeout      50000
        stats enable
        stats uri     /statspage
        stats refresh 5s
        stats show-node

frontend service1
        bind 127.0.0.1:10001
        default_backend linkerd

frontend service2
        bind 127.0.0.1:10002
        default_backend linkerd

frontend service3
        bind 127.0.0.1:10003
        default_backend linkerd

frontend service4
        bind 127.0.01:10004
        default_backend linkerd

frontend service5
        bind 127.0.01:10005
        default_backend linkerd

frontend service6
        bind 127.0.01:10006
        default_backend linkerd

backend linkerd
        option httpclose
        server localhost 127.0.0.1:4041
```

### shell
```sh
$ curl http://localhost:10006/index.html
# routes to "/s/service6-read" using the consul datacenter "cluster_1" with a fallback to "cluster_2"

$ curl -X POST -d @foo.json http://localhost:10006/nomnom
# routes to "/s/service-6-write" using the consul datacenter "cluster_1" with a fallback to "cluster_2"

$ curl -H 'Dtab-Local: /s/localhost:10005=>/s/service1' http://localhost:10005/index.html
# routes to "/s/service1" using the consul datacenter "cluster_1" with a fallback to "cluster_2"
```
